/* GENERATED by bun run generate:tokens from the contract version repo.config.json pins.
 * Edit the contract and raise the pin; an edit here survives until the next emit and then goes.
 * Every doc comment below is that token's own $description, and check:doc-comments fails one that is not. */

package org.dravensoft.arena.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Immutable
public data class ArenaDensityScale(
    /** control height (buttons, inputs, switches row) */
    public val ctlH: Dp,
    public val ctlHLg: Dp,
    public val ctlHSm: Dp,
    /** glyph-tight line height: the control reset. Unlike every other dz member this is unitless, so it carries its own $type override: a line height is a number, not a dimension, the same distinction that puts lh in typography.json to begin with. Used wherever a box must be exactly its glyph (an icon inside a button, a standalone icon, an icon-only close/remove control), so the line box never throws the surrounding control out of alignment. */
    public val lh: Float,
    /** row horizontal padding */
    public val rowPx: Dp,
    /** table/list row vertical padding */
    public val rowPy: Dp,
    /** gap between stacked items */
    public val stack: Dp,
    /** control text: buttons, inputs, selects, menu items, table cells */
    public val text: TextUnit,
    /** column headers, row micro-labels, and a chart's axis ticks. It is also where step-label is born, so the whole label register sits here until a style plugin moves it */
    public val text2xs: TextUnit,
    /** the largest control text: a data readout inside a chart, where the number is the content rather than a label */
    public val textLg: TextUnit,
    /** secondary control text: tag chips, pagination, secondary buttons */
    public val textMd: TextUnit,
    /** secondary control text: hints, validation errors, badges, legends */
    public val textSm: TextUnit,
    /** micro control text: field labels, shortcuts, eyebrow labels, and the category and point labels of a chart, which are chrome under a plot rather than prose */
    public val textXs: TextUnit
)

public val ArenaBaseDensity: ArenaDensityScale = ArenaDensityScale(
    ctlH = 40.dp,
    ctlHLg = 48.dp,
    ctlHSm = 32.dp,
    lh = 1f,
    rowPx = 16.dp,
    rowPy = 12.dp,
    stack = 12.dp,
    text = 14.sp,
    text2xs = 10.sp,
    textLg = 16.sp,
    textMd = 13.sp,
    textSm = 12.sp,
    textXs = 11.sp,
)

public val ArenaCompactDensity: ArenaDensityScale = ArenaDensityScale(
    ctlH = 32.dp,
    ctlHLg = 40.dp,
    ctlHSm = 26.dp,
    lh = 1f,
    rowPx = 12.dp,
    rowPy = 7.dp,
    stack = 8.dp,
    text = 13.sp,
    text2xs = 10.sp,
    textLg = 16.sp,
    textMd = 12.sp,
    textSm = 11.sp,
    textXs = 10.sp,
)

public val ArenaComfortableDensity: ArenaDensityScale = ArenaDensityScale(
    ctlH = 48.dp,
    ctlHLg = 56.dp,
    ctlHSm = 44.dp,
    lh = 1f,
    rowPx = 20.dp,
    rowPy = 16.dp,
    stack = 16.dp,
    text = 14.sp,
    text2xs = 10.sp,
    textLg = 16.sp,
    textMd = 13.sp,
    textSm = 12.sp,
    textXs = 11.sp,
)
