/* GENERATED by bun run generate:tokens from the contract version repo.config.json pins.
 * Edit the contract and raise the pin; an edit here survives until the next emit and then goes.
 * Every doc comment below is that token's own $description, and check:doc-comments fails one that is not. */

package org.dravensoft.arena.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

public object ArenaTokens {
    public val avatarLg: Dp = 56.dp
    public val avatarMd: Dp = 40.dp
    public val avatarSm: Dp = 32.dp
    /**
     * Script-readable, and so are its three siblings, for one reason: an <img>
     * reserves its box before the stylesheet arrives through the width and height
     * attributes, which take a bare integer and cannot take a custom property. So the
     * number has to reach JavaScript or the avatar is the one image in the library
     * whose space is not held. Reading it here rather than restating it in each layer
     * is what keeps the reserved box and the drawn box the same number.
     */
    public val avatarXs: Dp = 24.dp
    public val bpLg: Dp = 1024.dp
    public val bpMd: Dp = 768.dp
    public val bpSm: Dp = 480.dp
    /** Borders */
    public val bw: Dp = 1.dp
    public val bwStrong: Dp = 2.dp
    /**
     * The shortest chip that can carry its kebab below its title rather than
     * beside it. Measured: 4px of padding, a 15px title line, the 32px kebab and 4px
     * of padding again is 55px, rounded up to the 4px scale. Below it the two would
     * overlap, so the chip keeps reserving a lateral band instead. Script-readable
     * because it is compared against a projected pixel height.
     */
    public val calendarActionsBelowMinH: Dp = 56.dp
    /**
     * The width of the hour-label gutter down the left of the grid.
     * Script-readable because the width term of arenaShowsTime() subtracts it from the
     * measured container to get the grid's width, and no CSS expression hands a
     * number to JS. It was calc(var(--sp-1) * 14) rendered inline: the same value in
     * two idioms with nothing holding them in step. One token now, read both ways.
     */
    public val calendarGutterW: Dp = 56.dp
    /**
     * The pixel height of one hour. Script-readable because
     * y = ((min - startMin) / 60) * hour-h is arithmetic, and no CSS expression
     * computes a position from a minute-of-day. An orphan before this: --sp-10 is 40
     * and --sp-12 is 48, so nothing in the spacing scale was 44.
     */
    public val calendarHourH: Dp = 44.dp
    /**
     * The shortest chip that still draws its time label. Below it there is no
     * room for a second line. Script-readable because it is compared against a
     * projected pixel height; it was a bare 32 in the render body, invisible to
     * check:dimensions, which reads governed CSS properties and never a comparison.
     */
    public val calendarTimeMinH: Dp = 32.dp
    /**
     * The narrowest column share a chip may occupy and still draw its time
     * label. Measured: the label is 78.02px at --dz-text-2xs, and a chip's content box
     * is its share less 18px -- 4px of gutter to its neighbour, 12px of its own
     * padding, 2px of its left border -- so 96.02px, rounded up to the 4px scale. The
     * threshold is on the share rather than on the chip so that ArenaCalendar never has to
     * know ArenaCalendarEvent's padding.
     */
    public val calendarTimeMinW: Dp = 100.dp
    /** Surface between bars. Equals --bw-strong, coincidentally. */
    public val chartBarGap: Dp = 2.dp
    /**
     * A bar's data end. Deliberately NOT --r-sm (6px): naming the value Arena
     * already renders is free, snapping to the radius scale is a visible 2px design
     * change and must be taken as one.
     */
    public val chartBarRadius: Dp = 4.dp
    /**
     * A bubble at the largest value it carries. The pair is a RADIUS range and the
     * mapping between them is by area, not by radius: doubling a radius quadruples the blot, and a
     * reader compares the blot, so a linear radius exaggerates the large value by a factor of four.
     * Sixteen is what fits the size key beside the series names without either crowding the other,
     * and it is a chosen dimension rather than a consequence, unlike the pads.
     */
    public val chartBubbleRMax: Dp = 16.dp
    /**
     * A bubble at the smallest value it carries. Equals point-r, deliberately: a bubble
     * chart with one size in it is a scatter, and it should draw like one rather than jumping to
     * some other mark size the moment a third column appears.
     */
    public val chartBubbleRMin: Dp = 4.dp
    /** Plot height before padding. */
    public val chartHeight: Dp = 280.dp
    /**
     * Between an axis label and the plot it labels: a y-axis tick label ends this far
     * left of pad-left, and an x-axis category label sits this far above the bottom
     * edge. It is a spacing decision, so it is a token by the same criterion the pads
     * are.
     */
    public val chartLabelGap: Dp = 8.dp
    /** Between the doughnut plot and its legend. */
    public val chartLegendGap: Dp = 16.dp
    /** Doughnut legend, widest. */
    public val chartLegendMax: Dp = 180.dp
    /** Doughnut legend, narrowest. */
    public val chartLegendMin: Dp = 120.dp
    /**
     * The row of series keys a cartesian chart draws below its plot, height including
     * the separation from the plot. A CONSEQUENCE of the type scale rather than a chosen
     * dimension, the way pad-bottom is: one line at --dz-text-sm stands 18px at the root line
     * height, the swatch beside it is smaller and rides inside that line, and one step of the base
     * grid separates the row from the plot. If the type scale moves, revisit it; it will not fail
     * loudly.
     * It comes OUT of the plot rather than being added to the chart's box, so --chart-height stays
     * the height of the whole component whether a legend is drawn or not. That is the same trade
     * the doughnut already makes on the other axis, where the legend column takes its width from
     * the ring rather than from the caller.
     */
    public val chartLegendStrip: Dp = 26.dp
    /**
     * Holds the category labels. This is a CONSEQUENCE of the type scale, not a
     * chosen dimension: it is enough room for a label at --dz-text-xs, which is the step a
     * category label takes because a name under a plot is chrome and not prose. If the type
     * scale moves, revisit it; it will not fail loudly.
     * The labels stay on this edge whatever the data does, so a bar growing down from a
     * zero line above the floor runs toward them. That is deliberate: a reader looks for
     * category labels along the bottom, and moving them to follow the zero line would put
     * them somewhere different in every chart on a page. What it costs is a downward bar
     * reaching its label at the extreme of the axis, which is the price of one place to
     * look.
     */
    public val chartPadBottom: Dp = 28.dp
    /**
     * Holds the category names down the left edge of a horizontal bar chart, where
     * pad-left holds value labels on a vertical one. A separate token rather than a wider
     * pad-left, because the two hold different things and sizing every chart's value gutter for
     * the longest category name anyone might write would waste 52px on every vertical chart in
     * the library. A CONSEQUENCE of the type scale like pad-bottom, and a soft one: a name longer
     * than it fits is truncated rather than overrunning the plot, so this is the width at which a
     * reader stops needing the tooltip to read a label, not a limit on what may be passed.
     */
    public val chartPadCategory: Dp = 96.dp
    /** Holds the value labels. A consequence of the type scale, like pad-bottom. */
    public val chartPadLeft: Dp = 44.dp
    /** The plot's right padding, one step of the base grid. */
    public val chartPadRight: Dp = 8.dp
    /** The plot's top padding, one step of the base grid. */
    public val chartPadTop: Dp = 8.dp
    /** A line chart's point at rest. */
    public val chartPointR: Dp = 4.dp
    /**
     * A line chart's point under the pointer. The 1px delta IS the hover
     * affordance: the pair only means anything together.
     */
    public val chartPointRHover: Dp = 5.dp
    /**
     * Breathing room between the doughnut's outer radius and its box, so a slice's
     * stroke is not clipped. Not a multiplier deriving one dimension from another --
     * those stay inline by the recorded criterion -- but a chosen gap, which is why
     * this one is a token and the 0.62 inner-radius ratio beside it is not.
     */
    public val chartRingInset: Dp = 8.dp
    /**
     * Between two bars of the same category, when a chart draws more than one series.
     * Distinct from bar-gap, which is between categories, and deliberately smaller than it:
     * the wider gap is what tells a reader where one category ends, and if the two were equal
     * a grouped chart would read as one long row of unrelated bars. Script-readable, because
     * JS subtracts it from a sub-band width to produce an SVG x.
     */
    public val chartSeriesGap: Dp = 1.dp
    /**
     * The advance of one character of a tick label, which is what lets the axis measure
     * its widest tick without a DOM to ask. A CONSEQUENCE of two decisions rather than a
     * chosen dimension: a tick is written in the mono face, whose advance is 0.6em, at
     * --dz-text-2xs, which is 10px in both densities. Measured in the browser at 6.0016px
     * and rounded down to the whole pixel, because the gutter takes the ceiling of what it
     * computes and a hundredth of a pixel per character is not room anybody can see. It
     * holds only while the ticks stay monospaced: a proportional face makes a label's width
     * its glyphs' business and no arithmetic can answer it.
     */
    public val chartTickChar: Dp = 6.dp
    /**
     * Between the mark under the pointer and the tooltip's near edge. Not script-readable:
     * the chart interpolates the mark's own y into a calc() and CSS subtracts this from it, so
     * the stylesheet is what consumes the token. It settles a disagreement rather than recording
     * one: the bar chart offset its tooltip by --sp-2 and the line chart by 2.5 steps of --sp-1,
     * which is 10px against 8px for the same affordance. Naming it moves the line chart's tooltip
     * 2px, and that is a visible design change taken deliberately, the same way chart.bar-radius
     * refuses to snap to --r-sm because doing so would be one.
     */
    public val chartTooltipOffset: Dp = 8.dp
    /**
     * Grace period after the pointer leaves. Short, and much shorter than open:
     * it exists so travelling between a trigger and its own tooltip does not dismiss it,
     * not to keep the tooltip around.
     */
    public val delayClose: Int = 120
    /** Rest time before a tooltip appears. Long enough that crossing a toolbar reveals nothing. */
    public val delayOpen: Int = 400
    /**
     * A toast carrying a button. WCAG 2.2.1: it asks the reader to DECIDE, not
     * only to read, and 4.2s is enough for the second task only if they were already
     * looking. persist (README H1) still overrides both and stays mandatory in
     * critical states.
     */
    public val dismissActionable: Int = 7000
    /**
     * A toast that only has to be read. This is the value the Delivery Console
     * shipped hard-coded before it was a token.
     */
    public val dismissDefault: Int = 4200
    public val durFast: Int = 120
    public val durMid: Int = 220
    public val durSlow: Int = 420
    /** the "rotor" flourish */
    public val easeEmphatic: ArenaEasing = ArenaEasing(0.2f, 0.9f, 0.1f, 1f)
    public val easeInOut: ArenaEasing = ArenaEasing(0.4f, 0f, 0.2f, 1f)
    public val easeOut: ArenaEasing = ArenaEasing(0.2f, 0.7f, 0.3f, 1f)
    public val focusOffset: Dp = 2.dp
    public val focusWidth: Dp = 2.dp
    /** legible body copy */
    public val fontBody: String = "Familjen Grotesk"
    /** impact: headlines, wordmark */
    public val fontDisplay: String = "Archivo"
    /** data, technical labels */
    public val fontMono: String = "Spline Sans Mono"
    /** large display heading */
    public val fsDisplay: TextUnit = 64.sp
    public val fsH1: TextUnit = 44.sp
    public val fsH2: TextUnit = 32.sp
    public val fsH3: TextUnit = 24.sp
    public val fsH4: TextUnit = 19.sp
    /** extrapolated step between display (64) and mega (150) that keeps the scale's accelerating ratio coherent through its top; added with no consumer today by design: do not delete as dead API */
    public val fsHero: TextUnit = 96.sp
    public val fsLg: TextUnit = 17.sp
    /** body copy */
    public val fsMd: TextUnit = 15.sp
    /** largest display step: the brand manual's .big-glyph specimen */
    public val fsMega: TextUnit = 150.sp
    public val fsSm: TextUnit = 13.sp
    /** mono labels / captions */
    public val fsXs: TextUnit = 11.sp
    public val fwBlack: FontWeight = FontWeight(900)
    public val fwBold: FontWeight = FontWeight(700)
    public val fwExtrabold: FontWeight = FontWeight(800)
    public val fwMedium: FontWeight = FontWeight(500)
    public val fwRegular: FontWeight = FontWeight(400)
    public val fwSemibold: FontWeight = FontWeight(600)
    public val iconLg: TextUnit = 18.sp
    public val iconMd: TextUnit = 16.sp
    public val iconSm: TextUnit = 14.sp
    /** Illustration-scale icon (ArenaEmptyState, ArenaErrorState): a distinct role from the 14/16/18 inline-control cluster. */
    public val iconXl: TextUnit = 34.sp
    /**
     * The height of a fixed bottom navigation bar, the row of destinations a
     * phone shell puts at the foot of the screen. It is read from outside the bar as often
     * as inside it: the page reserves it as bottom padding so the last row is not covered,
     * and a stack of toasts sits above it rather than under it, so a bar whose height only
     * the bar knows is a number retyped in three files. The safe-area inset is NOT included:
     * add the bottom safe area to it, which ArenaSafeArea.bottom composes, since a value that
     * already carried the inset could not be used as a plain height. Nothing computes a
     * position from it, and a value bound at import time could not re-densify.
     */
    public val layoutBar: Dp = 64.dp
    /** The width of the console shell's navigation column. */
    public val layoutSidebar: Dp = 232.dp
    public val lhBody: Float = 1.6f
    /**
     * Reading leading for a style plugin that carries its hierarchy in type rather than in boxes.
     * One step above body, which is where a page of prose stops being a panel of copy.
     */
    public val lhLoose: Float = 1.8f
    /** What every element inherits until something declares otherwise. It is not a role like the three below, which a component picks on purpose; it is the floor, and it exists because a floor that each platform gets from somewhere else is a floor the two do not share. Tailwind's preflight sets exactly this number, so the Angular layer already had it and React, which loads no preflight, inherited the browser's `normal` instead: the same text stood about 7% shorter there, across 94 slots in 32 components, and nothing said so. Arena declares it now, in contracts/design/reset.css, so both layers inherit one value. The number matches what was already shipping rather than being chosen afresh. */
    public val lhRoot: Float = 1.5f
    public val lhSnug: Float = 1.15f
    public val lhTight: Float = 0.98f
    /**
     * How many page numbers flank the current one before the list elides. The
     * window's total width is a CONSEQUENCE and is derived at the point of use, never
     * authored: first + last + (2 * siblings + 1) + two ellipses.
     */
    public val limitPaginationSiblings: Float = 1f
    /** the manual's Primary · horizontal */
    public val logoMarkLg: Dp = 54.dp
    /** a signed-out panel's lock-up */
    public val logoMarkMd: Dp = 40.dp
    /** beside a product name in an application frame */
    public val logoMarkSm: Dp = 30.dp
    /** the hero case: the lock-up is the only thing on the screen */
    public val logoMarkXl: Dp = 124.dp
    /** the wordmark beside mark-lg, in the manual's Primary · horizontal */
    public val logoTextLg: Dp = 34.dp
    /** the wordmark beside mark-md, in a signed-out panel */
    public val logoTextMd: Dp = 24.dp
    /** the wordmark beside mark-sm: the smallest that still reads as a name rather than a label */
    public val logoTextSm: Dp = 17.dp
    /** the wordmark beside mark-xl, at hero size */
    public val logoTextXl: Dp = 78.dp
    /** Rotor: slow enough to read as presence rather than progress */
    public val loopBrand: Int = 8000
    /** Rotor's reduced step: the brand mark is three times slower again, because it is decoration that happens to also mean 'alive' */
    public val loopBrandReduced: Int = 24000
    /** What a working loop slows to under prefers-reduced-motion. Motion that reports work slows rather than stopping: a frozen spinner reads as a hung process. */
    public val loopReduced: Int = 2400
    /** ArenaSkeleton */
    public val loopShimmer: Int = 1400
    /** ArenaSpinner, and ArenaButton's loading ring */
    public val loopSpin: Int = 700
    /** ArenaProgressBar's indeterminate sweep */
    public val loopSweep: Int = 1150
    /** badge and pill text */
    public val lsBadge: TextUnit = 0.1.em
    /** column header / micro-label */
    public val lsColumnHeader: TextUnit = 0.12.em
    /** form field label */
    public val lsFieldLabel: TextUnit = 0.14.em
    /** mono uppercase labels: section eyebrows */
    public val lsLabel: TextUnit = 0.22.em
    /** mono navigation: breadcrumbs, bulk-action counts */
    public val lsMonoNav: TextUnit = 0.04.em
    public val lsNormal: TextUnit = 0.em
    /** display: tight headings */
    public val lsTight: TextUnit = (-0.02).em
    /** uppercase status text: alerts, toasts, calendar hour labels */
    public val lsUppercaseStatus: TextUnit = 0.06.em
    /** eyebrows */
    public val lsWide: TextUnit = 0.34.em
    /**
     * How much room the popover keeps below its anchor before it stops following it
     * down the viewport. Script-readable for the same reason width is: it is compared
     * against window.innerHeight in JS. It sat inline in both layers as a bare 220
     * beside a bare 900, and only one of the two is a design value -- 900 is an
     * SSR fallback for a viewport height nobody chose.
     */
    public val onboardingHeightReserve: Dp = 220.dp
    /**
     * The popover's width. Script-readable because Math.min/Math.max compare it
     * against window.innerWidth. This ALSO replaces the calc(var(--sp-1) * 80) the
     * component rendered: the value existed twice in two idioms, held in step by a
     * comment. One token now, read both ways.
     */
    public val onboardingWidth: Dp = 320.dp
    /** splash tile: distinct from xl's app icon tile */
    public val r2xl: Dp = 34.dp
    /** cards, panels */
    public val rLg: Dp = 14.dp
    /** nested cards, menus */
    public val rMd: Dp = 10.dp
    public val rPill: Dp = 999.dp
    /** buttons, inputs, chips */
    public val rSm: Dp = 6.dp
    /** app icon tile */
    public val rXl: Dp = 22.dp
    public val rXs: Dp = 4.dp
    /** Between two peer components: a card and the next card, a chart and the table under it. Both sides are separate things standing on the same footing. */
    public val rhythmComponent: Dp = 16.dp
    /** Inside one group of related things: a label and its field, a card's own stacked children, a row of chips. Both sides read as one unit. */
    public val rhythmGroup: Dp = 12.dp
    /** Between two sections of a page. The two sides answer different questions, and this gap is what says so. */
    public val rhythmSection: Dp = 24.dp
    /**
     * Overlay scrim: backdrop for anything that covers the app (ArenaDialog,
     * ConfirmDialog, ArenaCommandPalette, ArenaOnboarding). The blur is what separates a
     * modal from a coachmark: ArenaDialog/ArenaConfirmDialog/ArenaCommandPalette pair the scrim
     * with --scrim-blur, ArenaOnboarding uses the scrim alone, because a tour that
     * blurs the product it is touring defeats itself.
     */
    public val scrim: Color = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 0.6f)
    public val scrimBlur: Dp = 6.dp
    public val shadow1: ArenaShadow = ArenaShadow(offsetX = 0.dp, offsetY = 2.dp, blur = 6.dp, color = Color(red = 0f, green = 0f, blue = 0f, alpha = 0.5f))
    public val shadow2: ArenaShadow = ArenaShadow(offsetX = 0.dp, offsetY = 12.dp, blur = 28.dp, color = Color(red = 0f, green = 0f, blue = 0f, alpha = 0.6f))
    public val shadow3: ArenaShadow = ArenaShadow(offsetX = 0.dp, offsetY = 30.dp, blur = 60.dp, color = Color(red = 0f, green = 0f, blue = 0f, alpha = 0.7f))
    public val sp0: Dp = 0.dp
    /** Script-readable: ArenaMenu's gap from its trigger is one and a half of this, and that gap is the offset a CDK overlay position strategy computes in JS, so no stylesheet can hold it. */
    public val sp1: Dp = 4.dp
    public val sp10: Dp = 40.dp
    public val sp12: Dp = 48.dp
    public val sp16: Dp = 64.dp
    /** Script-readable: ArenaTooltip's gap from its trigger is the offset a CDK overlay position strategy computes in JS, so no stylesheet can hold it. */
    public val sp2: Dp = 8.dp
    public val sp20: Dp = 80.dp
    public val sp24: Dp = 96.dp
    /** Script-readable: ArenaOnboarding's gap below its anchor is arithmetic on a DOMRect. */
    public val sp3: Dp = 12.dp
    /** Script-readable: ArenaOnboarding's minimum gutter from either viewport edge, compared against window.innerWidth. */
    public val sp4: Dp = 16.dp
    public val sp5: Dp = 20.dp
    public val sp6: Dp = 24.dp
    public val sp8: Dp = 32.dp
    /** Fill under a line chart's series. A tint, never a gradient. */
    public val tintArea: Float = 0.18f
    /**
     * The hairline around that surface. It reads as the same colour only because
     * it is roughly twice soft: a border at the surface's own ratio disappears.
     */
    public val tintEdge: Float = 0.26f
    /**
     * The surface an identity colour stands on: light enough that text at the
     * body contrast keeps its ratio over it, which is why it is well under area.
     */
    public val tintSoft: Float = 0.12f
    /** ArenaMenu's panel: a dropdown anchored to its trigger */
    public val zDropdown: Float = 900f
    /** ArenaDialog */
    public val zModal: Float = 1000f
    /** ArenaConfirmDialog, which opens from an ArenaDialog */
    public val zModalNested: Float = 1050f
    /** Fixed page navigation: a bottom bar, a sticky top bar. Arena draws one of these, ArenaBottomNav, and the slot is not there for it: it is there because the invariant is system-wide and a consumer's own shell is part of the system, so a host's sticky header and Arena's bar interleave with Arena's overlays by design rather than by stacking order. That was the reason before any component carried it and it is the reason still; what changed is only that the set of things standing on this step is no longer empty. Below dropdown, so an ArenaMenu opened from the bar covers it rather than resolving by the order it was drawn in, which is the failure this family was created to end. Anything drawn against this slot also reads the bottom safe area, which ArenaSafeArea.bottom composes, and layoutBar for its own height */
    public val zNav: Float = 800f
    /** the coachmark and the scrim beneath it: one slot, two uses. The scrim takes the slot and the coachmark is drawn inside it, so the two are separated by containment rather than by a second number; nothing else on the page may sit between them, which is what a single slot means here */
    public val zOnboarding: Float = 1200f
    /** ArenaCommandPalette */
    public val zPalette: Float = 1100f
    /** A non-modal panel anchored to an edge: a cart, a filter drawer, a detail pane that leaves the page usable behind it. Arena draws one of these, ArenaSheet, and the slot exists for the same reason nav does: a host's own edge panel stands beside it on the same step. Above nav, because a sheet that slides over a fixed bar and lands under it is the failure; below dropdown, because an ArenaMenu opened from inside the sheet belongs over it. It is NOT modal: a panel that takes the whole interaction is an ArenaDialog, which is two slots higher and has a scrim to say so */
    public val zSheet: Float = 850f
    /** The skip link, while it holds focus. It is the one thing on the page that must cover the furniture it exists to bypass: a link that lands under a sticky header is a link nobody can read, and equal numbers resolve by DOM order, which puts the header on top because the skip link is deliberately first in the document. So it is above nav and no higher: everything from sheet upward is a surface that has taken the interaction, and a skip link floating over a modal is a route out of a trap that is meant to hold */
    public val zSkip: Float = 820f
    /** floats above everything, including onboarding: a transient notice raised by an action taken inside a dialog must stay visible */
    public val zToast: Float = 1300f
    /** above dropdown, so a tooltip on a menu item wins */
    public val zTooltip: Float = 950f
}
