/* GENERATED by bun run generate:tokens from the contract version repo.config.json pins.
 * Edit the contract and raise the pin; an edit here survives until the next emit and then goes.
 * Every doc comment below is that token's own $description, and check:doc-comments fails one that is not. */

package org.dravensoft.arena.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
public data class ArenaColorScheme(
    /** main background */
    public val base100: Color,
    /** elevated surface / card */
    public val base200: Color,
    /** panel / border */
    public val base300: Color,
    /** text on base */
    public val baseContent: Color,
    /**
     * Categorical chart ramp: identity only, never meaning (see README → Theming).
     * Fixed order: slot N is always slot N. A 9th series folds to "Other", small
     * multiples, or direct labels; it is NEVER a generated hue.
     * Chroma is capped at OKLCH C <= 0.15 so the ramp sits in Arena's register
     * (crimson .177, gold .100) instead of reading as neon.
     * forest  136°
     */
    public val cat1: Color,
    /** indigo  264° */
    public val cat2: Color,
    /** green   152° */
    public val cat3: Color,
    /** violet  288° */
    public val cat4: Color,
    /** cyan    216° */
    public val cat5: Color,
    /** purple  312° */
    public val cat6: Color,
    /** teal    184° */
    public val cat7: Color,
    /** orchid  328° */
    public val cat8: Color,
    /**
     * Outline danger: this red IS the text and the border, so it is tuned against
     * the base surfaces, lighter than the shared #e53e3e it replaced (4.29:1 on
     * base-200: under AA).
     */
    public val error: Color,
    public val errorContent: Color,
    /**
     * Filled danger. --color-error is tuned to be read AS TEXT on the base
     * surfaces, which makes it far too light to carry white text itself. The one
     * filled danger surface (ArenaConfirmDialog's final confirmation) therefore takes
     * its own fill, dark enough for --color-error-content. The two cannot be one
     * token: the outline needs a lighter red and the fill a darker one, in
     * opposite directions. This pin is OPTIONAL: omit it and colors.css derives
     * the fill from --color-error by darkening in oklab; the Dravensoft skin pins
     * it for an exact tone. Both gates are machine-checked: check-text-contrast.ts.
     */
    public val errorFill: Color,
    public val info: Color,
    public val infoContent: Color,
    /** neutral surface */
    public val neutral: Color,
    public val neutralContent: Color,
    /** crimson */
    public val primary: Color,
    public val primaryContent: Color,
    /** gold */
    public val secondary: Color,
    public val secondaryContent: Color,
    public val success: Color,
    public val successContent: Color,
    public val warning: Color,
    public val warningContent: Color
)

public val ArenaDarkColors: ArenaColorScheme = ArenaColorScheme(
    base100 = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
    base200 = Color(red = 0.1137f, green = 0.0902f, blue = 0.0824f, alpha = 1f),
    base300 = Color(red = 0.1412f, green = 0.1098f, blue = 0.098f, alpha = 1f),
    baseContent = Color(red = 0.9529f, green = 0.9294f, blue = 0.898f, alpha = 1f),
    cat1 = Color(red = 0.2353f, green = 0.4824f, blue = 0.0392f, alpha = 1f),
    cat2 = Color(red = 0.2314f, green = 0.3882f, blue = 0.7451f, alpha = 1f),
    cat3 = Color(red = 0.0392f, green = 0.5725f, blue = 0.2941f, alpha = 1f),
    cat4 = Color(red = 0.4157f, green = 0.349f, blue = 0.7373f, alpha = 1f),
    cat5 = Color(red = 0f, green = 0.6392f, blue = 0.7529f, alpha = 1f),
    cat6 = Color(red = 0.5333f, green = 0.302f, blue = 0.6627f, alpha = 1f),
    cat7 = Color(red = 0f, green = 0.6627f, blue = 0.6039f, alpha = 1f),
    cat8 = Color(red = 0.5961f, green = 0.2745f, blue = 0.5922f, alpha = 1f),
    error = Color(red = 0.9098f, green = 0.3176f, blue = 0.3176f, alpha = 1f),
    errorContent = Color(red = 1f, green = 1f, blue = 1f, alpha = 1f),
    errorFill = Color(red = 0.8078f, green = 0.2196f, blue = 0.2196f, alpha = 1f),
    info = Color(red = 0.1922f, green = 0.5098f, blue = 0.8078f, alpha = 1f),
    infoContent = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
    neutral = Color(red = 0.1725f, green = 0.1333f, blue = 0.1176f, alpha = 1f),
    neutralContent = Color(red = 0.8471f, green = 0.8118f, blue = 0.7686f, alpha = 1f),
    primary = Color(red = 0.7098f, green = 0.1647f, blue = 0.1255f, alpha = 1f),
    primaryContent = Color(red = 1f, green = 1f, blue = 1f, alpha = 1f),
    secondary = Color(red = 0.7725f, green = 0.6275f, blue = 0.349f, alpha = 1f),
    secondaryContent = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
    success = Color(red = 0.2196f, green = 0.6314f, blue = 0.4118f, alpha = 1f),
    successContent = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
    warning = Color(red = 0.9255f, green = 0.7882f, blue = 0.2941f, alpha = 1f),
    warningContent = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
)

public val ArenaLightColors: ArenaColorScheme = ArenaColorScheme(
    base100 = Color(red = 1f, green = 1f, blue = 1f, alpha = 1f),
    base200 = Color(red = 0.9686f, green = 0.9569f, blue = 0.9373f, alpha = 1f),
    base300 = Color(red = 0.9255f, green = 0.902f, blue = 0.8627f, alpha = 1f),
    baseContent = Color(red = 0.102f, green = 0.102f, blue = 0.102f, alpha = 1f),
    cat1 = Color(red = 0.2235f, green = 0.4706f, blue = 0.0157f, alpha = 1f),
    cat2 = Color(red = 0.149f, green = 0.2941f, blue = 0.6431f, alpha = 1f),
    cat3 = Color(red = 0.0392f, green = 0.5725f, blue = 0.2941f, alpha = 1f),
    cat4 = Color(red = 0.3216f, green = 0.2431f, blue = 0.6235f, alpha = 1f),
    cat5 = Color(red = 0f, green = 0.5608f, blue = 0.6627f, alpha = 1f),
    cat6 = Color(red = 0.4314f, green = 0.1961f, blue = 0.5529f, alpha = 1f),
    cat7 = Color(red = 0f, green = 0.5804f, blue = 0.5294f, alpha = 1f),
    cat8 = Color(red = 0.4863f, green = 0.1686f, blue = 0.4824f, alpha = 1f),
    error = Color(red = 0.7647f, green = 0.2078f, blue = 0.2078f, alpha = 1f),
    errorContent = Color(red = 1f, green = 1f, blue = 1f, alpha = 1f),
    errorFill = Color(red = 0.8078f, green = 0.2196f, blue = 0.2196f, alpha = 1f),
    info = Color(red = 0.1922f, green = 0.5098f, blue = 0.8078f, alpha = 1f),
    infoContent = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
    neutral = Color(red = 0.7922f, green = 0.7373f, blue = 0.6784f, alpha = 1f),
    neutralContent = Color(red = 0.2275f, green = 0.1804f, blue = 0.1608f, alpha = 1f),
    primary = Color(red = 0.7098f, green = 0.1647f, blue = 0.1255f, alpha = 1f),
    primaryContent = Color(red = 1f, green = 1f, blue = 1f, alpha = 1f),
    secondary = Color(red = 0.7725f, green = 0.6275f, blue = 0.349f, alpha = 1f),
    secondaryContent = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
    success = Color(red = 0.2196f, green = 0.6314f, blue = 0.4118f, alpha = 1f),
    successContent = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
    warning = Color(red = 0.9255f, green = 0.7882f, blue = 0.2941f, alpha = 1f),
    warningContent = Color(red = 0.0784f, green = 0.0627f, blue = 0.0627f, alpha = 1f),
)
