/* GENERATED by bun run generate:api-types from the contract version repo.config.json pins.
 * Edit the contract and raise the pin; an edit here survives until the next emit and then goes.
 * Every doc comment below is its contract's own description, and check:doc-comments fails one that is not. */

package org.dravensoft.arena.api

/** One event in a feed: someone did something to something, then. Arena draws every field: a consumer cannot place their own markup inside a row. */
public data class ArenaActivityItem(
    /** Who. Drawn bold in --bone. */
    public val actor: String,
    /** What they did. Drawn in --bone-dim. */
    public val action: String,
    /** A stable identity for the row, so a reordered feed does not re-key by index. */
    public val id: String? = null,
    /** What they did it to. Drawn monospaced in --gold: it is an identifier. */
    public val target: String? = null,
    /** When. Monospaced --mute, pushed to the trailing edge. Preformatted: ArenaActivityFeed never formats. */
    public val time: String? = null,
    /** The same moment as an ISO 8601 string, which is the machine-readable half of what the row shows. Present, the row carries it beside its own text; absent, the text is drawn as before. Two fields rather than one because time is what a reader sees and is deliberately whatever the consumer preformatted, up to "3 min ago", which no parser can resolve to a date. The pair is what lets Arena carry the timestamp itself, which is the only way it can: a field inside an array of predefined objects can only be a primitive, so a consumer cannot place their own content inside one row of a list Arena renders, and the convention that says so is not being lifted here. */
    public val dateTime: String? = null,
    /** ArenaBadge's vocabulary, driving the leading dot. Defaults to accent. */
    public val tone: ArenaTone? = null,
)

/** The alert's severity: the colour and default icon/role it takes. */
public enum class ArenaAlertTone(public val value: String) {
    Info("info"),
    Success("success"),
    Warning("warning"),
    Danger("danger"),
    Neutral("neutral");

    public companion object {
        public fun from(value: String): ArenaAlertTone? = entries.firstOrNull { it.value == value }
    }
}

/** Circle for a person, rounded for a team or organisation. */
public enum class ArenaAvatarShape(public val value: String) {
    Circle("circle"),
    Rounded("rounded");

    public companion object {
        public fun from(value: String): ArenaAvatarShape? = entries.firstOrNull { it.value == value }
    }
}

/** The avatar's diameter, a fixed repertoire: xs a dense table row, sm a comment byline, md the default, lg a profile header. */
public enum class ArenaAvatarSize(public val value: String) {
    Xs("xs"),
    Sm("sm"),
    Md("md"),
    Lg("lg");

    public companion object {
        public fun from(value: String): ArenaAvatarSize? = entries.firstOrNull { it.value == value }
    }
}

/** A presence state, drawn as a filled dot in the corner in the state's colour: `offline` is a visible muted dot, not the absence of one. There is no invisible value: to show no presence at all, omit the optional `status` member. */
public enum class ArenaAvatarStatus(public val value: String) {
    Online("online"),
    Busy("busy"),
    Away("away"),
    Offline("offline");

    public companion object {
        public fun from(value: String): ArenaAvatarStatus? = entries.firstOrNull { it.value == value }
    }
}

/** One action an ArenaBulkActionBar offers for the current selection. A destructive action stays outline in --error (transparent at rest, the soft --danger-soft tint only on hover), never the filled danger surface, which is ArenaConfirmDialog's alone. */
public data class ArenaBulkAction(
    /** A stable identity for the action, so a host can switch on it rather than on the label. */
    public val id: String,
    /** The button's text. */
    public val label: String,
    /** A Phosphor class name for the leading glyph Arena draws. */
    public val icon: String? = null,
    /** Renders the action outline in --error rather than in --bone-dim. */
    public val destructive: Boolean? = null,
)

/** Whether the bar may stack when its own container is too narrow for one row. */
public enum class ArenaBulkActionBarLayout(public val value: String) {
    Auto("auto"),
    Inline("inline");

    public companion object {
        public fun from(value: String): ArenaBulkActionBarLayout? = entries.firstOrNull { it.value == value }
    }
}

/** The native button behaviour. 'button' does nothing on its own and is the right default outside a form; 'submit' is what a bare <button> silently defaults to inside one, which is the footgun this member exists to make explicit. */
public enum class ArenaButtonType(public val value: String) {
    Button("button"),
    Submit("submit"),
    Reset("reset");

    public companion object {
        public fun from(value: String): ArenaButtonType? = entries.firstOrNull { it.value == value }
    }
}

/** Primary for the one main action in a view; secondary for neutral actions; ghost for tertiary ones; danger for destructive ones. Danger is outline and never filled: Arena's only filled danger surface is the final confirmation inside ArenaConfirmDialog. */
public enum class ArenaButtonVariant(public val value: String) {
    Primary("primary"),
    Secondary("secondary"),
    Ghost("ghost"),
    Danger("danger");

    public companion object {
        public fun from(value: String): ArenaButtonVariant? = entries.firstOrNull { it.value == value }
    }
}

/** How much of the schedule is on screen at once: a whole week of columns, or one day. Omitted on the component, it is derived from the container width rather than chosen. */
public enum class ArenaCalendarView(public val value: String) {
    Week("week"),
    Day("day");

    public companion object {
        public fun from(value: String): ArenaCalendarView? = entries.firstOrNull { it.value == value }
    }
}

/** A slot in the categorical ramp, in fixed order and never cycled. Colour here means which thing, never what state. The same ramp the charts use (identity is one system across Arena, not one per component), but typed as an enum only here: a chart's own slot members still declare a bare number, which their runtime clamp makes safe rather than correct, and narrowing them is an open contract change and not a fact this type states. The bound is not authored here either: it is the count of categorical slots the palette declares, and the contract fails if this set stops matching it. */
public enum class ArenaCatSlot(public val value: Int) {
    Slot1(1),
    Slot2(2),
    Slot3(3),
    Slot4(4),
    Slot5(5),
    Slot6(6),
    Slot7(7),
    Slot8(8);

    public companion object {
        public fun from(value: Int): ArenaCatSlot? = entries.firstOrNull { it.value == value }
    }
}

/** How an ArenaTable column's cells align. Checked against every enum already declared here before it was added; ArenaPageHeadAlign is the near miss and is a different set: start/center on a flex axis, with no `right`, and a right-aligned column of figures is precisely what this exists for. */
public enum class ArenaCellAlign(public val value: String) {
    Left("left"),
    Center("center"),
    Right("right");

    public companion object {
        public fun from(value: String): ArenaCellAlign? = entries.firstOrNull { it.value == value }
    }
}

/** How a legend row arranges its label and its figure when the row is narrow. */
public enum class ArenaChartLegendLayout(public val value: String) {
    Auto("auto"),
    Inline("inline"),
    Stacked("stacked");

    public companion object {
        public fun from(value: String): ArenaChartLegendLayout? = entries.firstOrNull { it.value == value }
    }
}

/** Whether a ring chart keeps its hole or fills to the centre. An enum rather than an inner-radius ratio, because the ratio is a design decision the chart already owns: chart.ring-inset is a token and the 0.62 hole beside it deliberately is not, on the recorded ground that a multiplier deriving one dimension from another stays inline. A number here would hand that decision to the caller one value at a time. */
public enum class ArenaChartShape(public val value: String) {
    Doughnut("doughnut"),
    Pie("pie");

    public companion object {
        public fun from(value: String): ArenaChartShape? = entries.firstOrNull { it.value == value }
    }
}

/** One entry in an ArenaCommandPalette. `hint` is searched but never shown, so a command can be found by a synonym that never appears in its label. */
public data class ArenaCommand(
    /** A stable identity for the command, so a host can switch on it rather than on the label. */
    public val id: String,
    /** What the command is called, and the primary text searched. */
    public val label: String,
    /** Searched but never shown: a synonym that finds the command. */
    public val hint: String? = null,
    /** A Phosphor class name for the leading glyph Arena draws. */
    public val icon: String? = null,
    /** A heading the command is listed under, such as "Actions" or "Customers". Commands with no group list first and ungrouped, then each group in the order its first command appears, so the caller decides the running order by the order they pass. A flat list is what a caller concatenates four collections into, and the headings are the only thing that says which collection a row came from. */
    public val group: String? = null,
    /** Where running this command goes. Present, the row is a navigation target in its own right, which a keyboard accelerator over a list of destinations should be: the same split, and the same reason, as ArenaSideNavItem.href. It stays an option in the list, because the listbox pattern the palette binds requires that of every row, so a reader is told it is an option rather than a destination; the trade is deliberate, since losing that would break arrow navigation for every row in the list. A primary activation cancels the navigation and reports through `run`, which is what makes the pointer and the keyboard agree; a gesture asking for the destination somewhere else opens it there, emits nothing and leaves the palette open, because the reader asked for a second place to look rather than to leave this one. */
    public val route: String? = null,
    /** The keystroke shown at the row's trailing edge, monospaced. Display only: the palette does not bind it. */
    public val shortcut: String? = null,
)

/** The three-step size scale shared by Arena's controls. What each step measures is the component's own decision and only some of them re-densify: ArenaButton and ArenaIconButton take their heights from the density tokens, so they shrink with the rows around them in the compact density, while ArenaProgressBar's thickness and ArenaSpinner's diameter are spacing and icon tokens the compact density does not redefine. The enum is shared because all four implement the same three steps, not because they resolve them the same way. */
public enum class ArenaControlSize(public val value: String) {
    Sm("sm"),
    Md("md"),
    Lg("lg");

    public companion object {
        public fun from(value: String): ArenaControlSize? = entries.firstOrNull { it.value == value }
    }
}

/** One entry in a breadcrumb trail. `href` is omitted for the current page, which is never rendered as a link. */
public data class ArenaCrumb(
    /** What the crumb reads. */
    public val label: String,
    /** Where it goes. Absent on the last entry, the current location. A primary activation is cancelled and reported through `navigate`, so a router owns it. */
    public val href: String? = null,
)

/** Whether a change was GOOD. Separate from ArenaDirection because revenue down is negative and latency down is positive, and only the product knows which. Every sign renders outline, never filled. */
public enum class ArenaDeltaTone(public val value: String) {
    Neutral("neutral"),
    Positive("positive"),
    Negative("negative");

    public companion object {
        public fun from(value: String): ArenaDeltaTone? = entries.firstOrNull { it.value == value }
    }
}

/** Which way a number moved. Draws the arrow: nothing else. Deliberately separate from whether that movement was good. */
public enum class ArenaDirection(public val value: String) {
    Up("up"),
    Down("down");

    public companion object {
        public fun from(value: String): ArenaDirection? = entries.firstOrNull { it.value == value }
    }
}

/** How much air separates two cells. Checked against every enum already declared here before it was added; nothing carries this set. ArenaControlSize is the near miss and is a different question: it names how tall a control stands, and it has no `none` because a control of no height is not a size. Four named steps rather than the spacing scale restated: a set that merely repeats what the token layer already derives may only be an enum while something machine-checks the restatement, and there is nothing to tie a numeric step list back to. These four are a decision about rhythm, and each layer resolves its own step from the scale. */
public enum class ArenaGridGap(public val value: String) {
    None("none"),
    Sm("sm"),
    Md("md"),
    Lg("lg");

    public companion object {
        public fun from(value: String): ArenaGridGap? = entries.firstOrNull { it.value == value }
    }
}

/** Which rung of the document outline a title takes. Arena already declares a title ladder, hero over page head over section over card, and that ladder was a visual register alone: a style plugin re-pitches the four as a unit, while a reader walking headings met whichever rung each component had settled on for itself, which was one level deep or none at all. This is the same ladder said as structure. The value names the outline rung and nothing else, because a title is styled the same at every value, so choosing a level costs no appearance and a gate is what holds that. Each component defaults to its own rung, so a card inside a section nests with nobody saying so, and the member is there for the screens where the default rung is the wrong one. `none` draws the title with no heading at all, for a title that labels a surface rather than naming a region; a component whose title is required refuses `none` at runtime, since a title required because it names the thing it draws cannot also be told the name is not one. */
public enum class ArenaHeadingLevel(public val value: String) {
    H1("h1"),
    H2("h2"),
    H3("h3"),
    H4("h4"),
    None("none");

    public companion object {
        public fun from(value: String): ArenaHeadingLevel? = entries.firstOrNull { it.value == value }
    }
}

/** Whether a hero's words run from the start edge or sit centred in their column. ArenaPageHeadAlign carries this exact set for a different subject: that one aligns an actions block against a title across a row, and this aligns a whole column of text within itself. Sharing the name would have put a page head in the type of a member no page head is involved in, and the near miss is worth stating rather than leaving for a later reader to find. */
public enum class ArenaHeroAlign(public val value: String) {
    Start("start"),
    Center("center");

    public companion object {
        public fun from(value: String): ArenaHeroAlign? = entries.firstOrNull { it.value == value }
    }
}

/** How a hero arranges its words against its figure. Checked against every enum already declared here before it was added; nothing carries this set. Three arrangements rather than a boolean, because bleed is not split-with-the-figure-behind: stacked and split put the two side by side or one under the other and the figure keeps its own box, while bleed lays the words ON the figure and makes the wash under them load-bearing. A boolean would have hidden the third. */
public enum class ArenaHeroLayout(public val value: String) {
    Stacked("stacked"),
    Split("split"),
    Bleed("bleed");

    public companion object {
        public fun from(value: String): ArenaHeroLayout? = entries.firstOrNull { it.value == value }
    }
}

/** 'ghost' sits on a surface and shows its hairline border; 'solid' is the filled accent treatment. Danger is not among them: Arena's danger convention is outline, and an icon-only danger control has no room to say what it destroys. */
public enum class ArenaIconButtonVariant(public val value: String) {
    Ghost("ghost"),
    Solid("solid");

    public companion object {
        public fun from(value: String): ArenaIconButtonVariant? = entries.firstOrNull { it.value == value }
    }
}

/** The native input types Arena styles. Date/time use the native control -- Arena ships no DatePicker. */
public enum class ArenaInputType(public val value: String) {
    Text("text"),
    Email("email"),
    Password("password"),
    Search("search"),
    Tel("tel"),
    Url("url"),
    Number("number"),
    Date("date"),
    Time("time"),
    DatetimeLocal("datetime-local");

    public companion object {
        public fun from(value: String): ArenaInputType? = entries.firstOrNull { it.value == value }
    }
}

/** One term and the value against it. Both are strings, because the value of a row in a summary is a formatted answer rather than a component: a price, a method, an address, a count. A slot per row would have made the list a compound family and bought nothing, since every value in every list this replaces is text somebody already formatted. */
public data class ArenaKeyValueRow(
    /** What the row is about, and it names the value beside it. */
    public val term: String,
    /** The answer, and it is described by the term beside it. */
    public val value: String,
    /** Whether the value is a figure, and takes the mono face and tabular numerals so a column of them aligns by digit. A money column that does not is a column that jitters as it changes. */
    public val numeric: Boolean? = null,
)

/** Both halves of the brand lock-up at once: the mark's slot and the wordmark. A fixed repertoire, not a ratio: sm an application frame, md a signed-out panel, lg the manual's Primary, xl the hero case. */
public enum class ArenaLogoSize(public val value: String) {
    Sm("sm"),
    Md("md"),
    Lg("lg"),
    Xl("xl");

    public companion object {
        public fun from(value: String): ArenaLogoSize? = entries.firstOrNull { it.value == value }
    }
}

/** Which edge of the trigger the dropdown panel lines its own edge up with. Checked against every enum already declared here before it was added; nothing carries this pair. ArenaPageHeadAlign is the near miss and is a different set -- start/center on a flex axis, with no `end`, where a panel hanging off a trigger has two edges to anchor to and no centre. */
public enum class ArenaMenuAlign(public val value: String) {
    Start("start"),
    End("end");

    public companion object {
        public fun from(value: String): ArenaMenuAlign? = entries.firstOrNull { it.value == value }
    }
}

/** One entry in an ArenaMenu, and it is one of three shapes: an entry carrying `divider` draws a hairline rule, one carrying `header` draws a group label, and every other entry draws an activatable row. Every field is optional because of that -- no field is common to all three -- and there is no `id`, because a divider and a header have nothing to identify and `select` carries the whole item rather than a key into the list. */
public data class ArenaMenuItem(
    /** What the row reads. */
    public val label: String? = null,
    /** A Phosphor class name drawn before the label: Arena draws the glyph, the consumer names it. */
    public val icon: String? = null,
    /** The keyboard hint drawn right-aligned in the mono face. Display only: ArenaMenu binds no key for it. */
    public val shortcut: String? = null,
    /** Draws the row in the danger ink. Destructive entries go last. */
    public val destructive: Boolean? = null,
    /** The row is drawn muted and reports no `select`. */
    public val disabled: Boolean? = null,
    /** Draws a hairline rule in place of a row. Carries no other field. */
    public val divider: Boolean? = null,
    /** Draws a group label in place of a row. Carries no other field. */
    public val header: String? = null,
)

/** How a chart writes each number before the prefix and the suffix are added. Every field is a primitive, so this stays a datum the component renders from rather than a function it calls, which is why a chart takes a format and never a formatter. It exists because "format the numbers before binding them" is not possible: what a chart is handed is number[], and the formatting has to reach the axis ticks, the tooltip and the accessible table, which the chart writes afterwards. Every field being absent is the raw JavaScript number, which is what a chart drew before this type existed. */
public data class ArenaNumberFormat(
    /** A BCP-47 tag, such as "es-BO". Absent, the runtime's own default, which on a server is the SERVER's locale and on a client the reader's: pass it explicitly wherever a server render must match its hydration, the same hazard ArenaCalendar.timeZone carries. */
    public val locale: String? = null,
    /** How many digits after the decimal separator, fixed. Absent, the locale decides. This is where a chart stops needing its data rounded before it is bound: rounding in the model to make a label read well loses the value everywhere else it is used. */
    public val fractionDigits: Double? = null,
    /** Whether thousands are separated. True by default because a five-digit tick is unreadable without it; false for a year, an identifier, or anything whose digits are not a quantity. */
    public val grouping: Boolean? = null,
    /** Writes 48.2K rather than 48200. For an axis over a wide range, where a full number is wider than the space between two ticks. it applies to every number the chart writes, ticks and tooltip and table alike, because a tooltip disagreeing with the tick above it is worse than a long label. */
    public val compact: Boolean? = null,
)

/** Where the coachmark attaches: the two viewport coordinates it positions from. Declared as its own object rather than borrowed from a platform, because a contract states no platform's own types, and because these are the only two fields ArenaOnboarding reads. */
public data class ArenaOnboardingAnchor(
    /** The anchored element's left edge, in viewport pixels. Clamped inside the viewport before use. */
    public val left: Double,
    /** The anchored element's bottom edge, in viewport pixels. The coachmark sits below it. */
    public val bottom: Double,
)

/** One step of a guided tour. All three fields are optional so a step can carry only the ones it needs; Arena renders each conditionally. */
public data class ArenaOnboardingStep(
    /** Mono crimson microlabel above the title. */
    public val eyebrow: String? = null,
    /** The step's headline, and the coachmark's accessible name. */
    public val title: String? = null,
    /** A sentence or two explaining the feature this step presents. */
    public val body: String? = null,
)

/** Whether a component's parts lay out side by side or stacked: which axis it runs along. */
public enum class ArenaOrientation(public val value: String) {
    Horizontal("horizontal"),
    Vertical("vertical");

    public companion object {
        public fun from(value: String): ArenaOrientation? = entries.firstOrNull { it.value == value }
    }
}

/** How the actions block aligns against the title in ArenaPageHead's wide layout. */
public enum class ArenaPageHeadAlign(public val value: String) {
    Start("start"),
    Center("center");

    public companion object {
        public fun from(value: String): ArenaPageHeadAlign? = entries.firstOrNull { it.value == value }
    }
}

/** One plotted series of pairs: two parallel measurements, read at the same index. It is a separate type from ArenaSeries rather than a variant of it, because the two disagree about what a mark IS: an ArenaSeries value takes its place on the axis from its index, and a pair carries both coordinates. It is two arrays rather than an array of {x, y} because R1 refuses an array of objects, and the pairing by index is the same one every chart here already makes between labels and values, with the same rule when the two do not line up. */
public data class ArenaPointSeries(
    /** Names this series, for its rows in the accessible table and for a legend. Required and guarded for the reason ArenaSeries.label is: nothing can derive what a series is about. */
    public val label: String,
    /** The horizontal values, in order. Continuous rather than an index, which is what a scatter needs and what a chart spacing its marks by position cannot give. */
    public val x: List<Double>,
    /** The vertical values, in order, paired with `x` at the same index. A mark is drawn only where both arrays have a value, so the shorter one ends the series: a pair with half a coordinate is not a point, and inventing the other half is the one thing a chart may not do. */
    public val y: List<Double>,
    /** An optional third measurement per mark, drawn as the mark's SIZE, paired with `x` and `y` at the same index. A series that carries it turns its chart into a bubble chart. The mapping is by AREA and not by radius, because a reader compares the blot and doubling a radius quadruples it, so a linear radius would exaggerate the large value by a factor of four. Where a size is absent, at the series or at one index, the mark keeps the plain point radius and its table cell is empty: an unmeasured size is not a size of zero, and the mark still holds its place because its position WAS measured. */
    public val r: List<Double>? = null,
    /** One identity colour from the categorical ramp for the whole series. 1-based, clamped to the ramp, never cycled. Absent, the chart assigns the series its position in the list. */
    public val slot: Double? = null,
    /** Semantic colour, for a series that IS a state. Mutually exclusive with slot; passing both warns in development and tone wins. */
    public val tone: ArenaSeriesTone? = null,
)

/** How the meter is drawn. A bar reads along a row and a ring reads at a glance, which is why a table cell takes the first and a tile takes the second. Nothing else about the component moves: the same percentage, the same tone, the same accessible name, the same announcement. */
public enum class ArenaProgressShape(public val value: String) {
    Linear("linear"),
    Radial("radial");

    public companion object {
        public fun from(value: String): ArenaProgressShape? = entries.firstOrNull { it.value == value }
    }
}

/** The bar's colour. No neutral and no warning: a progress bar reports work, and work is either running, done or failed. */
public enum class ArenaProgressTone(public val value: String) {
    Accent("accent"),
    Gold("gold"),
    Success("success"),
    Danger("danger"),
    Info("info");

    public companion object {
        public fun from(value: String): ArenaProgressTone? = entries.firstOrNull { it.value == value }
    }
}

/** Whether a scrolled row settles on an item or wherever it was left. Two words and not a boolean, because the pair is a decision about how the row reads and a boolean would name only one half of it: snap says the row is a sequence of things and lands on one, flow says it is a strip and lands anywhere. Neither moves on its own, which is why nothing here answers prefers-reduced-motion and why the component is not named for a marquee. */
public enum class ArenaScrollerBehaviour(public val value: String) {
    Snap("snap"),
    Flow("flow");

    public companion object {
        public fun from(value: String): ArenaScrollerBehaviour? = entries.firstOrNull { it.value == value }
    }
}

/** How far a section's head stands from the body under it. Checked against every enum already declared here before it was added, and ArenaGridGap carries this exact set for a different subject: that one is the air between two CELLS, on both axes, and this is the air between a heading and the thing it names, on one. Sharing the name would have put grid in the type of a member no grid is involved in, and the near miss is worth stating rather than hiding, since a later reader will find them and wonder. Four named steps rather than a length, for the reason ArenaGridGap gives: these are a decision about rhythm and each layer resolves its own step from the scale. */
public enum class ArenaSectionRhythm(public val value: String) {
    None("none"),
    Sm("sm"),
    Md("md"),
    Lg("lg");

    public companion object {
        public fun from(value: String): ArenaSectionRhythm? = entries.firstOrNull { it.value == value }
    }
}

/** One option in an ArenaSegmentedControl. */
public data class ArenaSegmentOption(
    /** What the option selects, and what `change` carries. */
    public val value: String,
    /** What the option reads. One word: the track stops being compact past that. */
    public val label: String,
)

/** Compact or default. Both sit below ArenaButton on purpose: a filter never outweighs an action. Distinct from ArenaControlSize, which offers a large step this control does not. */
public enum class ArenaSegmentedControlSize(public val value: String) {
    Sm("sm"),
    Md("md");

    public companion object {
        public fun from(value: String): ArenaSegmentedControlSize? = entries.firstOrNull { it.value == value }
    }
}

/** One option in an ArenaSelect. */
public data class ArenaSelectOption(
    /** What the option submits, and what ArenaSelect's `value` is matched against. */
    public val value: String,
    /** What the option reads. Free to differ from the value. */
    public val label: String,
)

/** One plotted series: what it is called, its numbers in order, and the colour it carries. It is what replaced five loose members on every chart (values, seriesLabel, slot, slots and tone), because those five described ONE series and a chart that draws two had nowhere to put the second. The name is not decoration: it heads the series' own column in the accessible table and names the series in a legend, so a chart of three series says which is which without the reader guessing from colour alone. */
public data class ArenaSeries(
    /** Names this series, for its column in the accessible table and for a legend. Required and guarded rather than defaulted: "Series 2" satisfies a heading mechanically and tells a screen-reader user nothing, and nothing can derive what a series is about, which is the same reason ArenaTable.label is required. */
    public val label: String,
    /** The plotted numbers, in order, one per point or category. A series shorter than the labels stops early rather than padding, because a missing number and a zero are different facts and a chart may not invent the difference. */
    public val values: List<Double>,
    /** One identity colour from the categorical ramp for the whole series. 1-based, clamped to the ramp, never cycled. Absent, the chart assigns the series its position in the list, which is the rule rather than a starting point. */
    public val slot: Double? = null,
    /** Per-mark identity override, one ramp slot each. Wins over `slot`. For a chart whose marks are the identities rather than the series, which is what a single-series bar chart and a doughnut both are. */
    public val slots: List<Double>? = null,
    /** Semantic colour, for a series that IS a state. Mutually exclusive with slot/slots; passing both warns in development and tone wins, because a chart carries identity or meaning, never both. */
    public val tone: ArenaSeriesTone? = null,
)

/** For a series that IS a state (error rate, pass/fail) rather than an identity. A chart carries identity or meaning, never both; passing tone alongside slot/slots warns in development and tone wins. */
public enum class ArenaSeriesTone(public val value: String) {
    Success("success"),
    Warning("warning"),
    Danger("danger"),
    Info("info");

    public companion object {
        public fun from(value: String): ArenaSeriesTone? = entries.firstOrNull { it.value == value }
    }
}

/** Which edge the panel is anchored to. Checked against every enum already declared here before it was added; nothing carries this set. ArenaToastPlacement is the near miss and is a different question: a stack of notices names a CORNER and needs both axes, where a sheet spans the edge it is attached to and names one. There is no top: a panel spanning the top edge of a page is a banner, which is what ArenaAlert already is, and a sheet is a working surface a reader keeps open beside the page. The inline pair is start/end rather than left/right so a right-to-left reading flips it with the document. */
public enum class ArenaSheetPlacement(public val value: String) {
    Bottom("bottom"),
    Start("start"),
    End("end");

    public companion object {
        public fun from(value: String): ArenaSheetPlacement? = entries.firstOrNull { it.value == value }
    }
}

/** The shape the placeholder reserves: a single text line, a stack of lines, a block, or a circle. */
public enum class ArenaSkeletonVariant(public val value: String) {
    Text("text"),
    Line("line"),
    Block("block"),
    Circle("circle");

    public companion object {
        public fun from(value: String): ArenaSkeletonVariant? = entries.firstOrNull { it.value == value }
    }
}

/** Which way a column is ordered. Deliberately not ArenaDirection, which is a delta's arrow: up and down say which way a NUMBER moved, and ascending and descending say how a COLUMN is arranged. One set of names for both would read as the same idea in the two places it is not. */
public enum class ArenaSortDirection(public val value: String) {
    Asc("asc"),
    Desc("desc");

    public companion object {
        public fun from(value: String): ArenaSortDirection? = entries.firstOrNull { it.value == value }
    }
}

/** Colour for an indeterminate wait. 'accent' on a page surface, 'on-accent' inside a filled button. There is deliberately no success/warning/danger: a wait has no state to report, and a spinner tinted --danger would read as a failure that has not happened. */
public enum class ArenaSpinnerTone(public val value: String) {
    Accent("accent"),
    Gold("gold"),
    Neutral("neutral"),
    OnAccent("on-accent");

    public companion object {
        public fun from(value: String): ArenaSpinnerTone? = entries.firstOrNull { it.value == value }
    }
}

/** How a metric moved. Preformatted: ArenaStatCard never formats. The pill's colour says whether the change was GOOD, not which way it points, which is why direction and tone are separate fields. */
public data class ArenaStatDelta(
    /** Preformatted, e.g. "+12%" or "-340ms". */
    public val value: String,
    /** Which way the number moved. Draws the arrow: nothing else. */
    public val direction: ArenaDirection,
    /** Whether that movement is GOOD. Defaults to neutral: an unlabelled delta claims nothing. */
    public val tone: ArenaDeltaTone? = null,
)

/** The switch's overall size, from a dense sm to a prominent 2xl. */
public enum class ArenaSwitchSize(public val value: String) {
    Sm("sm"),
    Md("md"),
    Lg("lg"),
    Xl("xl"),
    Size2xl("2xl");

    public companion object {
        public fun from(value: String): ArenaSwitchSize? = entries.firstOrNull { it.value == value }
    }
}

/** How an ArenaTable column's cells render in card mode: `row` is a label/value pair, `block` is a full-width strip with no label whose contents sit at the end of it, which is the shape an actions cell wants. A long value takes `row` or a cell of its own: set to `block` it draws with the whole gap on its leading side. Checked against every enum already declared here; nothing carries this pair. ArenaSkeletonVariant is the only other declaration containing the value `block`, and it names a shape of placeholder rather than a layout. */
public enum class ArenaTableCellLayout(public val value: String) {
    Row("row"),
    Block("block");

    public companion object {
        public fun from(value: String): ArenaTableCellLayout? = entries.firstOrNull { it.value == value }
    }
}

/** One column's configuration. A column says how its cells are headed and set, never what markup goes in them -- the consumer writes an ArenaTableCell per cell. */
public data class ArenaTableColumn(
    /** The column's label, drawn in the header row. */
    public val header: String,
    /** How this column's cells align. */
    public val align: ArenaCellAlign? = null,
    /** A fixed width for the column. Omit to let the table distribute. */
    public val width: String? = null,
    /** Draw this column's cells in the mono face, figure-aligned, and in the gold ink -- for identifiers and figures. The ink is the half that does not travel outside a table: gold reads as an identifier, so a sale total in gold inside a card says the wrong thing. Each layer offers the face and the digit alignment on their own, for a figure the consumer draws elsewhere, and its usage document says how. */
    public val mono: Boolean? = null,
    /** Whether this column's header is an activation target. A declared boolean rather than "is sortChange bound?", because Arena never derives what it draws from what a consumer listens for, the same reason ArenaTableRow.interactive is one. It costs no tab stop: the header row is already row 0 of the grid's roving cursor, so a sortable header is activated with Enter or Space on the cell the user is already on. Without ArenaTable.sort no header is a target however many columns declare it, because a control that draws a direction it does not know is worse than no control. */
    public val sortable: Boolean? = null,
    /** How this column renders in card mode: a label/value pair, or a full-width strip with no label whose contents sit at its end, which suits an actions cell rather than a long value. */
    public val mobileLayout: ArenaTableCellLayout? = null,
)

/** Which page of a longer list is on screen. Present, ArenaTable draws its own ArenaPagination below the grid and names it from `label`. ArenaTable does not slice: it does not hold the rows, so the consumer passes the page they already sliced and ArenaTable draws the control over it. */
public data class ArenaTablePage(
    /** The current page, 1-based, the same counting ArenaPagination uses. */
    public val index: Double,
    /** How many rows a full page holds. ArenaTable needs it to say how many pages there are, not to cut anything. */
    public val size: Double,
    /** How many rows there are across every page. Required because the projected children are one page and the count of pages cannot be derived from them; it is also what lets ArenaTable notice that the current page has gone PAST THE END and ask for page 1. That is the only reset ArenaTable performs, and it is the narrower half of the one a consumer writes: filtering ten pages down to five while the reader sits on the third leaves the page in range, so ArenaTable says nothing and the reader is on page three of results they did not ask for. Resetting on every change of total would be wrong, since removing one row from page three of ten must move nobody, and a count alone does not distinguish the two cases. Whether a change of CRITERION returns the reader to the first page is the consumer's question, because the consumer is the one holding the criterion. */
    public val total: Double,
)

/** Whether ArenaTable draws the pager it knows about. It is an enum rather than a boolean on the ArenaTableSortControl precedent, which this member is the second reading of: how a control is REACHED is a decision with room to grow, and the two members answer the same question about the two things a table's own chrome can hold. */
public enum class ArenaTablePageControl(public val value: String) {
    Auto("auto"),
    None("none");

    public companion object {
        public fun from(value: String): ArenaTablePageControl? = entries.firstOrNull { it.value == value }
    }
}

/** Where the projected rows sit inside a longer list. A reader is told the size of the whole collection and the position of each row within it whenever the rows on screen are only part of it, and a render that projects part of a list is that condition, so this is what those two announcements carry. Bound, it answers them whatever the consumer slices by. Absent with `page` bound, they are derived from the page, because a page IS a slice and stating it twice is how the two disagree. Absent with `page` absent, the projected rows are the whole list and neither is announced, which is the same answer the pattern gives for a grid holding every row it has. */
public data class ArenaTableSlice(
    /** How many rows the whole list holds, counting the ones nobody projected and not the header row, which ArenaTable adds itself because the announced count includes it. `-1` is the answer for a list whose length is not known yet, and it reaches the announcement unchanged: a feed that loads as it scrolls says -1 rather than a number it would have to invent and correct. */
    public val total: Double,
    /** How many rows of the whole list come before the first row projected here, counting from 0, so a window at the top of the list passes 0. The announced position is 1-based and the header row takes 1, so ArenaTable does that arithmetic rather than the consumer: an offset that already counted from 1 is counted twice, and the reader is told a position one row past where they are. */
    public val offset: Double,
)

/** Which column the rows are ordered by, and which way. Controlled: ArenaTable draws the affordance and announces the order, and the consumer does the ordering, because ArenaTable does not hold the rows and pretending otherwise would be the error. Absent, no header is a sort target however many columns declare `sortable`. */
public data class ArenaTableSort(
    /** Which column, as its index in `columns`. An index rather than a key, because an ArenaTable's cells are already positional -- the nth ArenaTableCell takes the nth column -- so a key would be a second identity for a thing that already has one, and a required one on every column that a caller would have to invent. */
    public val column: Double,
    /** Which way that column is ordered. */
    public val direction: ArenaSortDirection,
)

/** How the sort affordance is reached in card mode, where there is no header row to activate. Above --bp-md the header row IS the control and this decides nothing. */
public enum class ArenaTableSortControl(public val value: String) {
    Auto("auto"),
    None("none");

    public companion object {
        public fun from(value: String): ArenaTableSortControl? = entries.firstOrNull { it.value == value }
    }
}

/** The tag's emphasis colour, per the ArenaBadge/ArenaTag tone taxonomy. */
public enum class ArenaTagTone(public val value: String) {
    Neutral("neutral"),
    Primary("primary"),
    Success("success"),
    Warning("warning"),
    Danger("danger");

    public companion object {
        public fun from(value: String): ArenaTagTone? = entries.firstOrNull { it.value == value }
    }
}

/** Which corner the stack of notices is pinned to, block edge first. Checked against every enum already declared here before it was added; nothing carries this set. ArenaMenuAlign is the near miss and is a different question: it names which edge of a trigger a panel lines up with, on one axis, where this names a corner of the viewport and needs both. The inline half is `start`/`end` rather than left/right so a right-to-left reading flips it with the document. */
public enum class ArenaToastPlacement(public val value: String) {
    TopStart("top-start"),
    TopEnd("top-end"),
    BottomStart("bottom-start"),
    BottomEnd("bottom-end");

    public companion object {
        public fun from(value: String): ArenaToastPlacement? = entries.firstOrNull { it.value == value }
    }
}

/** The side bar's colour. Narrower than ArenaTone: a toast reports an outcome, and there is no informational outcome a toast should interrupt for. */
public enum class ArenaToastTone(public val value: String) {
    Neutral("neutral"),
    Success("success"),
    Danger("danger"),
    Gold("gold");

    public companion object {
        public fun from(value: String): ArenaToastTone? = entries.firstOrNull { it.value == value }
    }
}

/** What state a value IS in right now, as against how it moved. ArenaBadge's vocabulary, so one set of tone names covers the system rather than a second set that is nearly the same. */
public enum class ArenaTone(public val value: String) {
    Neutral("neutral"),
    Accent("accent"),
    Gold("gold"),
    Success("success"),
    Warning("warning"),
    Danger("danger"),
    Info("info");

    public companion object {
        public fun from(value: String): ArenaTone? = entries.firstOrNull { it.value == value }
    }
}

/** When ArenaInput runs `validate`: on blur, or on every change. */
public enum class ArenaValidateOn(public val value: String) {
    Blur("blur"),
    Change("change");

    public companion object {
        public fun from(value: String): ArenaValidateOn? = entries.firstOrNull { it.value == value }
    }
}
