import { test, expect } from 'bun:test';
import {
  UNMARKED, UNTRACKED, bannerProblems, carriageReturnProblems, namingProblems,
  staleUnmarkedProblems, staleUntrackedProblems, trackingProblems, zeroTrackedProblem,
} from './check-generated.ts';
import { COMMAND } from '../../lib/arena/emit.ts';
import { TARGETS } from '../../generate/arena/generate-tokens.ts';

test('a generated file says so in its name', () => {
  expect(namingProblems(TARGETS)).toEqual([]);
  expect(namingProblems(['compose/src/main/kotlin/X.kt'])[0]).toContain('its name does not say so');
});

test('the first line names the command that writes it, so a reader does not have to guess', () => {
  expect(bannerProblems(['a.kt'], () => `/* GENERATED by ${COMMAND} ... */\n`)).toEqual([]);
  expect(bannerProblems(['a.kt'], () => 'val x = 1\n')[0]).toContain('does not name the command');
});

test('the emit is tracked, which is the opposite of what Arena does and is the architecture', () => {
  expect(trackingProblems(['a.kt'], new Set(['a.kt']))).toEqual([]);
  expect(trackingProblems(['a.kt'], new Set())[0]).toContain('nothing to compile');
});

test('UNTRACKED holds the payload and nothing else, each entry with its reason', () => {
  expect([...UNTRACKED.keys()]).toEqual(['.contracts/']);
  for (const [, why] of UNTRACKED) expect(why.length).toBeGreaterThan(40);
  expect(staleUntrackedProblems(new Set(['.contracts/arena.contracts.json']))[0]).toContain('is tracked');
  expect(staleUntrackedProblems(new Set(['README.md']))).toEqual([]);
});

test('UNMARKED names what can carry neither the infix nor a banner, and fails when it is gone', () => {
  expect([...UNMARKED.keys()]).toEqual(['gradle/wrapper/gradle-wrapper.jar']);
  expect(staleUnmarkedProblems(new Set(['gradle/wrapper/gradle-wrapper.jar']))).toEqual([]);
  expect(staleUnmarkedProblems(new Set())[0]).toContain('which is not tracked');
});

test('a tracked text file carrying a carriage return fails, which .gitattributes is the other half of', () => {
  expect(carriageReturnProblems(['a.kt'], () => Buffer.from('one\ntwo\n'))).toEqual([]);
  expect(carriageReturnProblems(['a.kt'], () => Buffer.from('one\r\ntwo\n'))[0]).toContain('carriage return');
  expect(carriageReturnProblems(['a.jar'], () => Buffer.from('one\r\n'))).toEqual([]);
});

test('git reporting nothing tracked is a failure and not an empty repository', () => {
  expect(zeroTrackedProblem([])).toContain('0 tracked files');
  expect(zeroTrackedProblem(['a'])).toBeNull();
});
