import { test, expect } from 'bun:test';
import {
  EMITTED, UNMARKED, UNTRACKED, bannerProblems, carriageReturnProblems, crlfPatterns, declaredCrlf,
  matchesAttribute, namingProblems, staleCrlfProblems, staleUnmarkedProblems,
  staleUntrackedProblems, trackingProblems, zeroTrackedProblem,
} from './check-generated.ts';
import { API_COMMAND, COMMAND } from '../../lib/arena/emit.ts';
import { TARGETS } from '../../generate/arena/generate-tokens.ts';
import { API_TARGETS } from '../../generate/arena/generate-api-types.ts';

test('a generated file says so in its name', () => {
  expect(namingProblems(TARGETS)).toEqual([]);
  expect(namingProblems(['compose/src/main/kotlin/X.kt'])[0]).toContain('its name does not say so');
});

test('the first line names the command that writes it, so a reader does not have to guess', () => {
  const one = new Map([['a.kt', COMMAND]]);
  expect(bannerProblems(one, () => `/* GENERATED by ${COMMAND} ... */\n`)).toEqual([]);
  expect(bannerProblems(one, () => 'val x = 1\n')[0]).toContain('does not name the command');
});

test('each emitted file is held to the command that writes IT, since the two emitters no longer share one', () => {
  const both = new Map([['tokens.kt', COMMAND], ['api.kt', API_COMMAND]]);
  expect(bannerProblems(both, (target) => `/* GENERATED by ${both.get(target)} */\n`)).toEqual([]);
  const swapped = bannerProblems(both, (target) => `/* GENERATED by ${target === 'api.kt' ? COMMAND : API_COMMAND} */\n`);
  expect(swapped).toHaveLength(2);
  expect(COMMAND).not.toBe(API_COMMAND);
});

test('EMITTED names every target of both emitters and the command each one is written by', () => {
  expect([...EMITTED.keys()]).toEqual([...TARGETS, ...API_TARGETS]);
  for (const target of TARGETS) expect(EMITTED.get(target)).toBe(COMMAND);
  for (const target of API_TARGETS) expect(EMITTED.get(target)).toBe(API_COMMAND);
});

test('the emit is tracked, which is the opposite of what Arena does and is the architecture', () => {
  expect(trackingProblems(['a.kt'], new Set(['a.kt']))).toEqual([]);
  expect(trackingProblems(['a.kt'], new Set())[0]).toContain('nothing to compile');
});

test('UNTRACKED holds the payload and nothing else, each entry with its reason', () => {
  expect([...UNTRACKED.keys()]).toEqual(['.contracts/']);
  for (const [, why] of UNTRACKED) expect(why.length).toBeGreaterThan(40);
  expect(staleUntrackedProblems(new Set(['.contracts/arena.contracts.json']))[0]).toContain('is tracked');
  expect(staleUntrackedProblems(new Set(['README.md']))).toEqual([]);
});

test('UNMARKED names what can carry neither the infix nor a banner, and fails when it is gone', () => {
  expect([...UNMARKED.keys()]).toEqual(['gradle/wrapper/gradle-wrapper.jar']);
  expect(staleUnmarkedProblems(new Set(['gradle/wrapper/gradle-wrapper.jar']))).toEqual([]);
  expect(staleUnmarkedProblems(new Set())[0]).toContain('which is not tracked');
});

test('a tracked text file carrying a carriage return fails, which .gitattributes is the other half of', () => {
  expect(carriageReturnProblems(['a.kt'], () => Buffer.from('one\ntwo\n'))).toEqual([]);
  expect(carriageReturnProblems(['a.kt'], () => Buffer.from('one\r\ntwo\n'))[0]).toContain('carriage return');
  expect(carriageReturnProblems(['a.jar'], () => Buffer.from('one\r\n'))).toEqual([]);
});

test('the exception is derived from .gitattributes and never kept as a second list', () => {
  const attributes = '* text=auto eol=lf\n# a comment eol=crlf\ngradlew.bat text eol=crlf\n';
  expect(crlfPatterns(attributes)).toEqual(['gradlew.bat']);
  expect(matchesAttribute('gradlew.bat', 'gradlew.bat')).toBe(true);
  expect(matchesAttribute('gradlew.bat', 'a/b/gradlew.bat')).toBe(true);
  expect(matchesAttribute('*.bat', 'a/x.bat')).toBe(true);
  expect(matchesAttribute('gradle/wrapper/x', 'gradle/wrapper/x')).toBe(true);
  expect(matchesAttribute('gradlew.bat', 'gradlew')).toBe(false);
  const allowed = declaredCrlf(['gradlew', 'gradlew.bat'], attributes);
  expect([...allowed]).toEqual(['gradlew.bat']);
  expect(carriageReturnProblems(['gradlew.bat'], () => Buffer.from('one\r\n'), allowed)).toEqual([]);
  expect(carriageReturnProblems(['gradlew'], () => Buffer.from('one\r\n'), allowed)[0]).toContain('carriage return');
});

test('a CRLF declaration matching no tracked file excepts nothing, and fails', () => {
  const attributes = 'gradlew.bat text eol=crlf\n';
  expect(staleCrlfProblems(['gradlew.bat'], attributes)).toEqual([]);
  expect(staleCrlfProblems(['gradlew'], attributes)[0]).toContain('excepts nothing');
});

test('git reporting nothing tracked is a failure and not an empty repository', () => {
  expect(zeroTrackedProblem([])).toContain('0 tracked files');
  expect(zeroTrackedProblem(['a'])).toBeNull();
});
