/* What both emitters agree on: the banner that names the command, the doc comment derived
 * from the contract's own $description, and the three sets a target is split into. The split
 * is the payload's and not a preference: two palette files declare the same names for two
 * themes, and three files declare the dz ladder for three densities, so a flat emit would
 * have each of them silently overwrite the last. */

import { byCodeUnit } from '../../utils/compare.ts';
import { identifierFor } from './identifier.ts';
import { bridge, type Emitted } from './bridge.ts';
import { inScope, type Density, type Theme, type Token } from '../contracts/payload.ts';

export const COMMAND = 'bun run generate:tokens';

export function banner(comment: '/*' | '//') {
  const lines = [
    `GENERATED by ${COMMAND} from the contract version repo.config.json pins.`,
    'Edit the contract and raise the pin; an edit here survives until the next emit and then goes.',
    'Every doc comment below is that token\'s own $description, and check:doc-comments fails one that is not.',
  ];
  if (comment === '//') return lines.map((line) => `// ${line}`).join('\n');
  return [`/* ${lines[0]}`, ` * ${lines[1]}`, ` * ${lines[2]} */`].join('\n');
}

export function kdoc(description: string | undefined, indent: string) {
  if (!description) return [];
  if (description.includes('*/')) {
    throw new Error(`a $description carrying "*/" cannot be emitted as KDoc without altering it, and altering it is what check:doc-comments refuses`);
  }
  const lines = description.split('\n').map((line) => line.trim());
  if (lines.length === 1) return [`${indent}/** ${lines[0]} */`];
  return [`${indent}/**`, ...lines.map((line) => `${indent} * ${line}`.trimEnd()), `${indent} */`];
}

export function tripleSlash(description: string | undefined, indent: string) {
  if (!description) return [];
  return description.split('\n').map((line) => `${indent}/// ${line.trim()}`.trimEnd());
}

export function flatten(description: string | undefined) {
  return (description ?? '').replace(/\s+/g, ' ').trim();
}

function emitted(tokens: Token[], drop: number) {
  return tokens
    .map((token) => bridge(token, identifierFor(token.path.slice(drop))))
    .sort((a, b) => byCodeUnit(a.identifier, b.identifier));
}

export function scaleTokens(all: Token[]) {
  return emitted(inScope(all, 'base').filter((token) => token.path[0] !== 'dz'), 0);
}

export function themeTokens(all: Token[], theme: Theme) {
  return emitted(inScope(all, theme), 1);
}

export function densityTokens(all: Token[], density: Density) {
  const base = inScope(all, 'base').filter((token) => token.path[0] === 'dz');
  if (density === 'base') return emitted(base, 1);
  const override = new Map(inScope(all, density).map((token) => [token.name, token]));
  return emitted(base.map((token) => override.get(token.name) ?? token), 1);
}

export function shapeProblems(all: Token[]) {
  const errs: string[] = [];
  const dark = new Map(themeTokens(all, 'dark').map((one) => [one.identifier, one]));
  const light = new Map(themeTokens(all, 'light').map((one) => [one.identifier, one]));
  for (const [identifier, one] of dark) {
    const pair = light.get(identifier);
    if (!pair) errs.push(`${one.token.name} is declared for dark and not for light, so the two schemes are not one shape`);
    else if (pair.swiftType !== one.swiftType) errs.push(`${one.token.name} is ${one.swiftType} in dark and ${pair.swiftType} in light`);
  }
  for (const [identifier, one] of light) {
    if (!dark.has(identifier)) errs.push(`${one.token.name} is declared for light and not for dark, so the two schemes are not one shape`);
  }
  const base = new Map(densityTokens(all, 'base').map((one) => [one.identifier, one]));
  for (const density of ['compact', 'comfortable'] as const) {
    for (const one of inScope(all, density)) {
      const identifier = identifierFor(one.path.slice(1));
      if (!base.has(identifier)) {
        errs.push(`${one.name} is declared in the ${density} density and not in the base ladder, so nothing it overrides exists`);
      }
    }
  }
  return errs.sort(byCodeUnit);
}

export type { Emitted };
