/* What both emitters agree on: the banner that names the command, the doc comment derived
 * from the contract's own $description, and the three sets a target is split into. The split
 * is the payload's and not a preference: two palette files declare the same names for two
 * themes, and three files declare the dz ladder for three densities, so a flat emit would
 * have each of them silently overwrite the last. */

import { byCodeUnit, sortedByCodeUnit } from '../../utils/compare.ts';
import { identifierFor } from './identifier.ts';
import { bridge, type Emitted } from './bridge.ts';
import { inScope, type Density, type Theme, type Token } from '../contracts/payload.ts';

export const COMMAND = 'bun run generate:tokens';
export const API_COMMAND = 'bun run generate:api-types';

export const TOKEN_SUBJECT = 'that token\'s own $description';
export const API_SUBJECT = 'its contract\'s own description';

export function banner(comment: '/*' | '//', command = COMMAND, subject = TOKEN_SUBJECT) {
  const lines = [
    `GENERATED by ${command} from the contract version repo.config.json pins.`,
    'Edit the contract and raise the pin; an edit here survives until the next emit and then goes.',
    `Every doc comment below is ${subject}, and check:doc-comments fails one that is not.`,
  ];
  if (comment === '//') return lines.map((line) => `// ${line}`).join('\n');
  return [`/* ${lines[0]}`, ` * ${lines[1]}`, ` * ${lines[2]} */`].join('\n');
}

export function kdoc(description: string | undefined, indent: string) {
  if (!description) return [];
  if (description.includes('*/')) {
    throw new Error(`a $description carrying "*/" cannot be emitted as KDoc without altering it, and altering it is what check:doc-comments refuses`);
  }
  const lines = description.split('\n').map((line) => line.trim());
  if (lines.length === 1) return [`${indent}/** ${lines[0]} */`];
  return [`${indent}/**`, ...lines.map((line) => `${indent} * ${line}`.trimEnd()), `${indent} */`];
}

export function tripleSlash(description: string | undefined, indent: string) {
  if (!description) return [];
  return description.split('\n').map((line) => `${indent}/// ${line.trim()}`.trimEnd());
}

export function flatten(description: string | undefined) {
  return (description ?? '').replace(/\s+/g, ' ').trim();
}

export const REPHRASED = new Map<string, { was: string; text: string; why: string }>([
  [
    'layout.bar',
    {
      was: "The height of a fixed bottom navigation bar, the row of destinations a\nphone shell puts at the foot of the screen. It is read from outside the bar as often\nas inside it: the page reserves it as bottom padding so the last row is not covered,\nand a stack of toasts sits above it rather than under it, so a bar whose height only\nthe bar knows is a number retyped in three files. The safe-area inset is NOT included:\nadd var(--pad-safe-bottom) to it, since a value that already carried the inset could\nnot be used as a plain height. Not script-readable: nothing computes a position from\nit, a stylesheet holds every use, and a number bound at import time could not\nre-densify.",
      text: "The height of a fixed bottom navigation bar, the row of destinations a\nphone shell puts at the foot of the screen. It is read from outside the bar as often\nas inside it: the page reserves it as bottom padding so the last row is not covered,\nand a stack of toasts sits above it rather than under it, so a bar whose height only\nthe bar knows is a number retyped in three files. The safe-area inset is NOT included:\nadd the bottom safe area to it, which ArenaSafeArea.bottom composes, since a value that\nalready carried the inset could not be used as a plain height. Nothing computes a\nposition from it, and a value bound at import time could not re-densify.",
      why: "the clause that goes names var(--pad-safe-bottom), a custom property this library composes as ArenaSafeArea.bottom instead, and a stylesheet that holds every use, which is the web layer describing where its own call sites live. Every claim the sentence makes about the height is true here and stays",
    },
  ],
  [
    'z.nav',
    {
      was: "Fixed page navigation: a bottom bar, a sticky top bar. Arena draws one of these, ArenaBottomNav, and the slot is not there for it: it is there because the invariant is system-wide and a consumer's own shell is part of the system, so a host's sticky header and Arena's bar interleave with Arena's overlays by design rather than by DOM order. That was the reason before any component carried it and it is the reason still; what changed is only that the set of things standing on this step is no longer empty. Below dropdown, so an ArenaMenu opened from the bar covers it rather than resolving by DOM order, which is the failure this family was created to end. Anything drawn against this slot also reads --pad-safe-bottom, in contracts/design/environment.css, and --layout-bar for its own height",
      text: "Fixed page navigation: a bottom bar, a sticky top bar. Arena draws one of these, ArenaBottomNav, and the slot is not there for it: it is there because the invariant is system-wide and a consumer's own shell is part of the system, so a host's sticky header and Arena's bar interleave with Arena's overlays by design rather than by stacking order. That was the reason before any component carried it and it is the reason still; what changed is only that the set of things standing on this step is no longer empty. Below dropdown, so an ArenaMenu opened from the bar covers it rather than resolving by the order it was drawn in, which is the failure this family was created to end. Anything drawn against this slot also reads the bottom safe area, which ArenaSafeArea.bottom composes, and layoutBar for its own height",
      why: "DOM order is the web spelling of the thing a stacking slot exists to overrule, and the last clause names a custom property and a file in the Arena repository. Both of the values it points at exist here, as ArenaSafeArea.bottom and as layoutBar, so each name is replaced by the thing it named",
    },
  ],
]);

export function docTextFor(name: string, description: string | undefined, rephrased = REPHRASED) {
  return rephrased.get(name)?.text ?? description;
}

export function staleRephrasedProblems(
  tokens: readonly { name: string; description?: string }[],
  rephrased = REPHRASED,
) {
  const carried = new Map(tokens.map((token) => [token.name, token.description]));
  return sortedByCodeUnit([...rephrased].flatMap(([name, { was, why }]) => {
    if (!carried.has(name)) {
      return [`REPHRASED names ${name}, and the payload declares no token by that name: ${why}`];
    }
    if (flatten(carried.get(name)) === flatten(was)) return [];
    return [`REPHRASED carries a stale copy of ${name}'s $description, so the replacement below was `
      + `written against text the contract no longer has and is emitted over the new one unread: ${why}`];
  }));
}

function emitted(tokens: Token[], drop: number) {
  return tokens
    .map((token) => bridge(token, identifierFor(token.path.slice(drop))))
    .sort((a, b) => byCodeUnit(a.identifier, b.identifier));
}

export function scaleTokens(all: Token[]) {
  return emitted(inScope(all, 'base').filter((token) => token.path[0] !== 'dz'), 0);
}

export function themeTokens(all: Token[], theme: Theme) {
  return emitted(inScope(all, theme), 1);
}

export function densityTokens(all: Token[], density: Density) {
  const base = inScope(all, 'base').filter((token) => token.path[0] === 'dz');
  if (density === 'base') return emitted(base, 1);
  const override = new Map(inScope(all, density).map((token) => [token.name, token]));
  return emitted(base.map((token) => override.get(token.name) ?? token), 1);
}

export function shapeProblems(all: Token[]) {
  const errs: string[] = [];
  const dark = new Map(themeTokens(all, 'dark').map((one) => [one.identifier, one]));
  const light = new Map(themeTokens(all, 'light').map((one) => [one.identifier, one]));
  for (const [identifier, one] of dark) {
    const pair = light.get(identifier);
    if (!pair) errs.push(`${one.token.name} is declared for dark and not for light, so the two schemes are not one shape`);
    else if (pair.swiftType !== one.swiftType) errs.push(`${one.token.name} is ${one.swiftType} in dark and ${pair.swiftType} in light`);
  }
  for (const [identifier, one] of light) {
    if (!dark.has(identifier)) errs.push(`${one.token.name} is declared for light and not for dark, so the two schemes are not one shape`);
  }
  const base = new Map(densityTokens(all, 'base').map((one) => [one.identifier, one]));
  for (const density of ['compact', 'comfortable'] as const) {
    for (const one of inScope(all, density)) {
      const identifier = identifierFor(one.path.slice(1));
      if (!base.has(identifier)) {
        errs.push(`${one.name} is declared in the ${density} density and not in the base ladder, so nothing it overrides exists`);
      }
    }
  }
  return errs.sort(byCodeUnit);
}

export type { Emitted };
