// GENERATED by bun run generate:api-types from the contract version repo.config.json pins.
// Edit the contract and raise the pin; an edit here survives until the next emit and then goes.
// Every doc comment below is its contract's own description, and check:doc-comments fails one that is not.

/// One event in a feed: someone did something to something, then. Arena draws every field: a consumer cannot place their own markup inside a row.
public struct ArenaActivityItem: Sendable {
    /// Who. Drawn bold in --bone.
    public let actor: String
    /// What they did. Drawn in --bone-dim.
    public let action: String
    /// A stable identity for the row, so a reordered feed does not re-key by index.
    public let id: String?
    /// What they did it to. Drawn monospaced in --gold: it is an identifier.
    public let target: String?
    /// When. Monospaced --mute, pushed to the trailing edge. Preformatted: ArenaActivityFeed never formats.
    public let time: String?
    /// The same moment as an ISO 8601 string, which is the machine-readable half of what the row shows. Present, the row carries it beside its own text; absent, the text is drawn as before. Two fields rather than one because time is what a reader sees and is deliberately whatever the consumer preformatted, up to "3 min ago", which no parser can resolve to a date. The pair is what lets Arena carry the timestamp itself, which is the only way it can: a field inside an array of predefined objects can only be a primitive, so a consumer cannot place their own content inside one row of a list Arena renders, and the convention that says so is not being lifted here.
    public let dateTime: String?
    /// ArenaBadge's vocabulary, driving the leading dot. Defaults to accent.
    public let tone: ArenaTone?

    public init(
        actor: String,
        action: String,
        id: String? = nil,
        target: String? = nil,
        time: String? = nil,
        dateTime: String? = nil,
        tone: ArenaTone? = nil
    ) {
        self.actor = actor
        self.action = action
        self.id = id
        self.target = target
        self.time = time
        self.dateTime = dateTime
        self.tone = tone
    }
}

/// The alert's severity: the colour and default icon/role it takes.
public enum ArenaAlertTone: String, CaseIterable, Sendable {
    case info = "info"
    case success = "success"
    case warning = "warning"
    case danger = "danger"
    case neutral = "neutral"
}

/// Circle for a person, rounded for a team or organisation.
public enum ArenaAvatarShape: String, CaseIterable, Sendable {
    case circle = "circle"
    case rounded = "rounded"
}

/// The avatar's diameter, a fixed repertoire: xs a dense table row, sm a comment byline, md the default, lg a profile header.
public enum ArenaAvatarSize: String, CaseIterable, Sendable {
    case xs = "xs"
    case sm = "sm"
    case md = "md"
    case lg = "lg"
}

/// A presence state, drawn as a filled dot in the corner in the state's colour: `offline` is a visible muted dot, not the absence of one. There is no invisible value: to show no presence at all, omit the optional `status` member.
public enum ArenaAvatarStatus: String, CaseIterable, Sendable {
    case online = "online"
    case busy = "busy"
    case away = "away"
    case offline = "offline"
}

/// One action an ArenaBulkActionBar offers for the current selection. A destructive action stays outline in --error (transparent at rest, the soft --danger-soft tint only on hover), never the filled danger surface, which is ArenaConfirmDialog's alone.
public struct ArenaBulkAction: Sendable {
    /// A stable identity for the action, so a host can switch on it rather than on the label.
    public let id: String
    /// The button's text.
    public let label: String
    /// A Phosphor class name for the leading glyph Arena draws.
    public let icon: String?
    /// Renders the action outline in --error rather than in --bone-dim.
    public let destructive: Bool?

    public init(
        id: String,
        label: String,
        icon: String? = nil,
        destructive: Bool? = nil
    ) {
        self.id = id
        self.label = label
        self.icon = icon
        self.destructive = destructive
    }
}

/// Whether the bar may stack when its own container is too narrow for one row.
public enum ArenaBulkActionBarLayout: String, CaseIterable, Sendable {
    case auto = "auto"
    case inline = "inline"
}

/// The native button behaviour. 'button' does nothing on its own and is the right default outside a form; 'submit' is what a bare <button> silently defaults to inside one, which is the footgun this member exists to make explicit.
public enum ArenaButtonType: String, CaseIterable, Sendable {
    case button = "button"
    case submit = "submit"
    case reset = "reset"
}

/// Primary for the one main action in a view; secondary for neutral actions; ghost for tertiary ones; danger for destructive ones. Danger is outline and never filled: Arena's only filled danger surface is the final confirmation inside ArenaConfirmDialog.
public enum ArenaButtonVariant: String, CaseIterable, Sendable {
    case primary = "primary"
    case secondary = "secondary"
    case ghost = "ghost"
    case danger = "danger"
}

/// How much of the schedule is on screen at once: a whole week of columns, or one day. Omitted on the component, it is derived from the container width rather than chosen.
public enum ArenaCalendarView: String, CaseIterable, Sendable {
    case week = "week"
    case day = "day"
}

/// A slot in the categorical ramp, in fixed order and never cycled. Colour here means which thing, never what state. The same ramp the charts use (identity is one system across Arena, not one per component), but typed as an enum only here: a chart's own slot members still declare a bare number, which their runtime clamp makes safe rather than correct, and narrowing them is an open contract change and not a fact this type states. The bound is not authored here either: it is the count of categorical slots the palette declares, and the contract fails if this set stops matching it.
public enum ArenaCatSlot: Int, CaseIterable, Sendable {
    case slot1 = 1
    case slot2 = 2
    case slot3 = 3
    case slot4 = 4
    case slot5 = 5
    case slot6 = 6
    case slot7 = 7
    case slot8 = 8
}

/// How an ArenaTable column's cells align. Checked against every enum already declared here before it was added; ArenaPageHeadAlign is the near miss and is a different set: start/center on a flex axis, with no `right`, and a right-aligned column of figures is precisely what this exists for.
public enum ArenaCellAlign: String, CaseIterable, Sendable {
    case left = "left"
    case center = "center"
    case right = "right"
}

/// How a legend row arranges its label and its figure when the row is narrow.
public enum ArenaChartLegendLayout: String, CaseIterable, Sendable {
    case auto = "auto"
    case inline = "inline"
    case stacked = "stacked"
}

/// Whether a ring chart keeps its hole or fills to the centre. An enum rather than an inner-radius ratio, because the ratio is a design decision the chart already owns: chart.ring-inset is a token and the 0.62 hole beside it deliberately is not, on the recorded ground that a multiplier deriving one dimension from another stays inline. A number here would hand that decision to the caller one value at a time.
public enum ArenaChartShape: String, CaseIterable, Sendable {
    case doughnut = "doughnut"
    case pie = "pie"
}

/// One entry in an ArenaCommandPalette. `hint` is searched but never shown, so a command can be found by a synonym that never appears in its label.
public struct ArenaCommand: Sendable {
    /// A stable identity for the command, so a host can switch on it rather than on the label.
    public let id: String
    /// What the command is called, and the primary text searched.
    public let label: String
    /// Searched but never shown: a synonym that finds the command.
    public let hint: String?
    /// A Phosphor class name for the leading glyph Arena draws.
    public let icon: String?
    /// A heading the command is listed under, such as "Actions" or "Customers". Commands with no group list first and ungrouped, then each group in the order its first command appears, so the caller decides the running order by the order they pass. A flat list is what a caller concatenates four collections into, and the headings are the only thing that says which collection a row came from.
    public let group: String?
    /// Where running this command goes. Present, the row is a navigation target in its own right, which a keyboard accelerator over a list of destinations should be: the same split, and the same reason, as ArenaSideNavItem.href. It stays an option in the list, because the listbox pattern the palette binds requires that of every row, so a reader is told it is an option rather than a destination; the trade is deliberate, since losing that would break arrow navigation for every row in the list. A primary activation cancels the navigation and reports through `run`, which is what makes the pointer and the keyboard agree; a gesture asking for the destination somewhere else opens it there, emits nothing and leaves the palette open, because the reader asked for a second place to look rather than to leave this one.
    public let route: String?
    /// The keystroke shown at the row's trailing edge, monospaced. Display only: the palette does not bind it.
    public let shortcut: String?

    public init(
        id: String,
        label: String,
        hint: String? = nil,
        icon: String? = nil,
        group: String? = nil,
        route: String? = nil,
        shortcut: String? = nil
    ) {
        self.id = id
        self.label = label
        self.hint = hint
        self.icon = icon
        self.group = group
        self.route = route
        self.shortcut = shortcut
    }
}

/// The three-step size scale shared by Arena's controls. What each step measures is the component's own decision and only some of them re-densify: ArenaButton and ArenaIconButton take their heights from the density tokens, so they shrink with the rows around them in the compact density, while ArenaProgressBar's thickness and ArenaSpinner's diameter are spacing and icon tokens the compact density does not redefine. The enum is shared because all four implement the same three steps, not because they resolve them the same way.
public enum ArenaControlSize: String, CaseIterable, Sendable {
    case sm = "sm"
    case md = "md"
    case lg = "lg"
}

/// One entry in a breadcrumb trail. `href` is omitted for the current page, which is never rendered as a link.
public struct ArenaCrumb: Sendable {
    /// What the crumb reads.
    public let label: String
    /// Where it goes. Absent on the last entry, the current location. A primary activation is cancelled and reported through `navigate`, so a router owns it.
    public let href: String?

    public init(
        label: String,
        href: String? = nil
    ) {
        self.label = label
        self.href = href
    }
}

/// Whether a change was GOOD. Separate from ArenaDirection because revenue down is negative and latency down is positive, and only the product knows which. Every sign renders outline, never filled.
public enum ArenaDeltaTone: String, CaseIterable, Sendable {
    case neutral = "neutral"
    case positive = "positive"
    case negative = "negative"
}

/// Which way a number moved. Draws the arrow: nothing else. Deliberately separate from whether that movement was good.
public enum ArenaDirection: String, CaseIterable, Sendable {
    case up = "up"
    case down = "down"
}

/// How much air separates two cells. Checked against every enum already declared here before it was added; nothing carries this set. ArenaControlSize is the near miss and is a different question: it names how tall a control stands, and it has no `none` because a control of no height is not a size. Four named steps rather than the spacing scale restated: a set that merely repeats what the token layer already derives may only be an enum while something machine-checks the restatement, and there is nothing to tie a numeric step list back to. These four are a decision about rhythm, and each layer resolves its own step from the scale.
public enum ArenaGridGap: String, CaseIterable, Sendable {
    case none = "none"
    case sm = "sm"
    case md = "md"
    case lg = "lg"
}

/// Which rung of the document outline a title takes. Arena already declares a title ladder, hero over page head over section over card, and that ladder was a visual register alone: a style plugin re-pitches the four as a unit, while a reader walking headings met whichever rung each component had settled on for itself, which was one level deep or none at all. This is the same ladder said as structure. The value names the outline rung and nothing else, because a title is styled the same at every value, so choosing a level costs no appearance and a gate is what holds that. Each component defaults to its own rung, so a card inside a section nests with nobody saying so, and the member is there for the screens where the default rung is the wrong one. `none` draws the title with no heading at all, for a title that labels a surface rather than naming a region; a component whose title is required refuses `none` at runtime, since a title required because it names the thing it draws cannot also be told the name is not one.
public enum ArenaHeadingLevel: String, CaseIterable, Sendable {
    case h1 = "h1"
    case h2 = "h2"
    case h3 = "h3"
    case h4 = "h4"
    case none = "none"
}

/// Whether a hero's words run from the start edge or sit centred in their column. ArenaPageHeadAlign carries this exact set for a different subject: that one aligns an actions block against a title across a row, and this aligns a whole column of text within itself. Sharing the name would have put a page head in the type of a member no page head is involved in, and the near miss is worth stating rather than leaving for a later reader to find.
public enum ArenaHeroAlign: String, CaseIterable, Sendable {
    case start = "start"
    case center = "center"
}

/// How a hero arranges its words against its figure. Checked against every enum already declared here before it was added; nothing carries this set. Three arrangements rather than a boolean, because bleed is not split-with-the-figure-behind: stacked and split put the two side by side or one under the other and the figure keeps its own box, while bleed lays the words ON the figure and makes the wash under them load-bearing. A boolean would have hidden the third.
public enum ArenaHeroLayout: String, CaseIterable, Sendable {
    case stacked = "stacked"
    case split = "split"
    case bleed = "bleed"
}

/// 'ghost' sits on a surface and shows its hairline border; 'solid' is the filled accent treatment. Danger is not among them: Arena's danger convention is outline, and an icon-only danger control has no room to say what it destroys.
public enum ArenaIconButtonVariant: String, CaseIterable, Sendable {
    case ghost = "ghost"
    case solid = "solid"
}

/// The native input types Arena styles. Date/time use the native control -- Arena ships no DatePicker.
public enum ArenaInputType: String, CaseIterable, Sendable {
    case text = "text"
    case email = "email"
    case password = "password"
    case search = "search"
    case tel = "tel"
    case url = "url"
    case number = "number"
    case date = "date"
    case time = "time"
    case datetimeLocal = "datetime-local"
}

/// One term and the value against it. Both are strings, because the value of a row in a summary is a formatted answer rather than a component: a price, a method, an address, a count. A slot per row would have made the list a compound family and bought nothing, since every value in every list this replaces is text somebody already formatted.
public struct ArenaKeyValueRow: Sendable {
    /// What the row is about, and it names the value beside it.
    public let term: String
    /// The answer, and it is described by the term beside it.
    public let value: String
    /// Whether the value is a figure, and takes the mono face and tabular numerals so a column of them aligns by digit. A money column that does not is a column that jitters as it changes.
    public let numeric: Bool?

    public init(
        term: String,
        value: String,
        numeric: Bool? = nil
    ) {
        self.term = term
        self.value = value
        self.numeric = numeric
    }
}

/// Both halves of the brand lock-up at once: the mark's slot and the wordmark. A fixed repertoire, not a ratio: sm an application frame, md a signed-out panel, lg the manual's Primary, xl the hero case.
public enum ArenaLogoSize: String, CaseIterable, Sendable {
    case sm = "sm"
    case md = "md"
    case lg = "lg"
    case xl = "xl"
}

/// Which edge of the trigger the dropdown panel lines its own edge up with. Checked against every enum already declared here before it was added; nothing carries this pair. ArenaPageHeadAlign is the near miss and is a different set -- start/center on a flex axis, with no `end`, where a panel hanging off a trigger has two edges to anchor to and no centre.
public enum ArenaMenuAlign: String, CaseIterable, Sendable {
    case start = "start"
    case end = "end"
}

/// One entry in an ArenaMenu, and it is one of three shapes: an entry carrying `divider` draws a hairline rule, one carrying `header` draws a group label, and every other entry draws an activatable row. Every field is optional because of that -- no field is common to all three -- and there is no `id`, because a divider and a header have nothing to identify and `select` carries the whole item rather than a key into the list.
public struct ArenaMenuItem: Sendable {
    /// What the row reads.
    public let label: String?
    /// A Phosphor class name drawn before the label: Arena draws the glyph, the consumer names it.
    public let icon: String?
    /// The keyboard hint drawn right-aligned in the mono face. Display only: ArenaMenu binds no key for it.
    public let shortcut: String?
    /// Draws the row in the danger ink. Destructive entries go last.
    public let destructive: Bool?
    /// The row is drawn muted and reports no `select`.
    public let disabled: Bool?
    /// Draws a hairline rule in place of a row. Carries no other field.
    public let divider: Bool?
    /// Draws a group label in place of a row. Carries no other field.
    public let header: String?

    public init(
        label: String? = nil,
        icon: String? = nil,
        shortcut: String? = nil,
        destructive: Bool? = nil,
        disabled: Bool? = nil,
        divider: Bool? = nil,
        header: String? = nil
    ) {
        self.label = label
        self.icon = icon
        self.shortcut = shortcut
        self.destructive = destructive
        self.disabled = disabled
        self.divider = divider
        self.header = header
    }
}

/// How a chart writes each number before the prefix and the suffix are added. Every field is a primitive, so this stays a datum the component renders from rather than a function it calls, which is why a chart takes a format and never a formatter. It exists because "format the numbers before binding them" is not possible: what a chart is handed is number[], and the formatting has to reach the axis ticks, the tooltip and the accessible table, which the chart writes afterwards. Every field being absent is the raw JavaScript number, which is what a chart drew before this type existed.
public struct ArenaNumberFormat: Sendable {
    /// A BCP-47 tag, such as "es-BO". Absent, the runtime's own default, which on a server is the SERVER's locale and on a client the reader's: pass it explicitly wherever a server render must match its hydration, the same hazard ArenaCalendar.timeZone carries.
    public let locale: String?
    /// How many digits after the decimal separator, fixed. Absent, the locale decides. This is where a chart stops needing its data rounded before it is bound: rounding in the model to make a label read well loses the value everywhere else it is used.
    public let fractionDigits: Double?
    /// Whether thousands are separated. True by default because a five-digit tick is unreadable without it; false for a year, an identifier, or anything whose digits are not a quantity.
    public let grouping: Bool?
    /// Writes 48.2K rather than 48200. For an axis over a wide range, where a full number is wider than the space between two ticks. it applies to every number the chart writes, ticks and tooltip and table alike, because a tooltip disagreeing with the tick above it is worse than a long label.
    public let compact: Bool?

    public init(
        locale: String? = nil,
        fractionDigits: Double? = nil,
        grouping: Bool? = nil,
        compact: Bool? = nil
    ) {
        self.locale = locale
        self.fractionDigits = fractionDigits
        self.grouping = grouping
        self.compact = compact
    }
}

/// Where the coachmark attaches: the two viewport coordinates it positions from. Declared as its own object rather than borrowed from a platform, because a contract states no platform's own types, and because these are the only two fields ArenaOnboarding reads.
public struct ArenaOnboardingAnchor: Sendable {
    /// The anchored element's left edge, in viewport pixels. Clamped inside the viewport before use.
    public let left: Double
    /// The anchored element's bottom edge, in viewport pixels. The coachmark sits below it.
    public let bottom: Double

    public init(
        left: Double,
        bottom: Double
    ) {
        self.left = left
        self.bottom = bottom
    }
}

/// One step of a guided tour. All three fields are optional so a step can carry only the ones it needs; Arena renders each conditionally.
public struct ArenaOnboardingStep: Sendable {
    /// Mono crimson microlabel above the title.
    public let eyebrow: String?
    /// The step's headline, and the coachmark's accessible name.
    public let title: String?
    /// A sentence or two explaining the feature this step presents.
    public let body: String?

    public init(
        eyebrow: String? = nil,
        title: String? = nil,
        body: String? = nil
    ) {
        self.eyebrow = eyebrow
        self.title = title
        self.body = body
    }
}

/// Whether a component's parts lay out side by side or stacked: which axis it runs along.
public enum ArenaOrientation: String, CaseIterable, Sendable {
    case horizontal = "horizontal"
    case vertical = "vertical"
}

/// How the actions block aligns against the title in ArenaPageHead's wide layout.
public enum ArenaPageHeadAlign: String, CaseIterable, Sendable {
    case start = "start"
    case center = "center"
}

/// One plotted series of pairs: two parallel measurements, read at the same index. It is a separate type from ArenaSeries rather than a variant of it, because the two disagree about what a mark IS: an ArenaSeries value takes its place on the axis from its index, and a pair carries both coordinates. It is two arrays rather than an array of {x, y} because R1 refuses an array of objects, and the pairing by index is the same one every chart here already makes between labels and values, with the same rule when the two do not line up.
public struct ArenaPointSeries: Sendable {
    /// Names this series, for its rows in the accessible table and for a legend. Required and guarded for the reason ArenaSeries.label is: nothing can derive what a series is about.
    public let label: String
    /// The horizontal values, in order. Continuous rather than an index, which is what a scatter needs and what a chart spacing its marks by position cannot give.
    public let x: [Double]
    /// The vertical values, in order, paired with `x` at the same index. A mark is drawn only where both arrays have a value, so the shorter one ends the series: a pair with half a coordinate is not a point, and inventing the other half is the one thing a chart may not do.
    public let y: [Double]
    /// An optional third measurement per mark, drawn as the mark's SIZE, paired with `x` and `y` at the same index. A series that carries it turns its chart into a bubble chart. The mapping is by AREA and not by radius, because a reader compares the blot and doubling a radius quadruples it, so a linear radius would exaggerate the large value by a factor of four. Where a size is absent, at the series or at one index, the mark keeps the plain point radius and its table cell is empty: an unmeasured size is not a size of zero, and the mark still holds its place because its position WAS measured.
    public let r: [Double]?
    /// One identity colour from the categorical ramp for the whole series. 1-based, clamped to the ramp, never cycled. Absent, the chart assigns the series its position in the list.
    public let slot: Double?
    /// Semantic colour, for a series that IS a state. Mutually exclusive with slot; passing both warns in development and tone wins.
    public let tone: ArenaSeriesTone?

    public init(
        label: String,
        x: [Double],
        y: [Double],
        r: [Double]? = nil,
        slot: Double? = nil,
        tone: ArenaSeriesTone? = nil
    ) {
        self.label = label
        self.x = x
        self.y = y
        self.r = r
        self.slot = slot
        self.tone = tone
    }
}

/// How the meter is drawn. A bar reads along a row and a ring reads at a glance, which is why a table cell takes the first and a tile takes the second. Nothing else about the component moves: the same percentage, the same tone, the same accessible name, the same announcement.
public enum ArenaProgressShape: String, CaseIterable, Sendable {
    case linear = "linear"
    case radial = "radial"
}

/// The bar's colour. No neutral and no warning: a progress bar reports work, and work is either running, done or failed.
public enum ArenaProgressTone: String, CaseIterable, Sendable {
    case accent = "accent"
    case gold = "gold"
    case success = "success"
    case danger = "danger"
    case info = "info"
}

/// Whether a scrolled row settles on an item or wherever it was left. Two words and not a boolean, because the pair is a decision about how the row reads and a boolean would name only one half of it: snap says the row is a sequence of things and lands on one, flow says it is a strip and lands anywhere. Neither moves on its own, which is why nothing here answers prefers-reduced-motion and why the component is not named for a marquee.
public enum ArenaScrollerBehaviour: String, CaseIterable, Sendable {
    case snap = "snap"
    case flow = "flow"
}

/// How far a section's head stands from the body under it. Checked against every enum already declared here before it was added, and ArenaGridGap carries this exact set for a different subject: that one is the air between two CELLS, on both axes, and this is the air between a heading and the thing it names, on one. Sharing the name would have put grid in the type of a member no grid is involved in, and the near miss is worth stating rather than hiding, since a later reader will find them and wonder. Four named steps rather than a length, for the reason ArenaGridGap gives: these are a decision about rhythm and each layer resolves its own step from the scale.
public enum ArenaSectionRhythm: String, CaseIterable, Sendable {
    case none = "none"
    case sm = "sm"
    case md = "md"
    case lg = "lg"
}

/// One option in an ArenaSegmentedControl.
public struct ArenaSegmentOption: Sendable {
    /// What the option selects, and what `change` carries.
    public let value: String
    /// What the option reads. One word: the track stops being compact past that.
    public let label: String

    public init(
        value: String,
        label: String
    ) {
        self.value = value
        self.label = label
    }
}

/// Compact or default. Both sit below ArenaButton on purpose: a filter never outweighs an action. Distinct from ArenaControlSize, which offers a large step this control does not.
public enum ArenaSegmentedControlSize: String, CaseIterable, Sendable {
    case sm = "sm"
    case md = "md"
}

/// One option in an ArenaSelect.
public struct ArenaSelectOption: Sendable {
    /// What the option submits, and what ArenaSelect's `value` is matched against.
    public let value: String
    /// What the option reads. Free to differ from the value.
    public let label: String

    public init(
        value: String,
        label: String
    ) {
        self.value = value
        self.label = label
    }
}

/// One plotted series: what it is called, its numbers in order, and the colour it carries. It is what replaced five loose members on every chart (values, seriesLabel, slot, slots and tone), because those five described ONE series and a chart that draws two had nowhere to put the second. The name is not decoration: it heads the series' own column in the accessible table and names the series in a legend, so a chart of three series says which is which without the reader guessing from colour alone.
public struct ArenaSeries: Sendable {
    /// Names this series, for its column in the accessible table and for a legend. Required and guarded rather than defaulted: "Series 2" satisfies a heading mechanically and tells a screen-reader user nothing, and nothing can derive what a series is about, which is the same reason ArenaTable.label is required.
    public let label: String
    /// The plotted numbers, in order, one per point or category. A series shorter than the labels stops early rather than padding, because a missing number and a zero are different facts and a chart may not invent the difference.
    public let values: [Double]
    /// One identity colour from the categorical ramp for the whole series. 1-based, clamped to the ramp, never cycled. Absent, the chart assigns the series its position in the list, which is the rule rather than a starting point.
    public let slot: Double?
    /// Per-mark identity override, one ramp slot each. Wins over `slot`. For a chart whose marks are the identities rather than the series, which is what a single-series bar chart and a doughnut both are.
    public let slots: [Double]?
    /// Semantic colour, for a series that IS a state. Mutually exclusive with slot/slots; passing both warns in development and tone wins, because a chart carries identity or meaning, never both.
    public let tone: ArenaSeriesTone?

    public init(
        label: String,
        values: [Double],
        slot: Double? = nil,
        slots: [Double]? = nil,
        tone: ArenaSeriesTone? = nil
    ) {
        self.label = label
        self.values = values
        self.slot = slot
        self.slots = slots
        self.tone = tone
    }
}

/// For a series that IS a state (error rate, pass/fail) rather than an identity. A chart carries identity or meaning, never both; passing tone alongside slot/slots warns in development and tone wins.
public enum ArenaSeriesTone: String, CaseIterable, Sendable {
    case success = "success"
    case warning = "warning"
    case danger = "danger"
    case info = "info"
}

/// Which edge the panel is anchored to. Checked against every enum already declared here before it was added; nothing carries this set. ArenaToastPlacement is the near miss and is a different question: a stack of notices names a CORNER and needs both axes, where a sheet spans the edge it is attached to and names one. There is no top: a panel spanning the top edge of a page is a banner, which is what ArenaAlert already is, and a sheet is a working surface a reader keeps open beside the page. The inline pair is start/end rather than left/right so a right-to-left reading flips it with the document.
public enum ArenaSheetPlacement: String, CaseIterable, Sendable {
    case bottom = "bottom"
    case start = "start"
    case end = "end"
}

/// The shape the placeholder reserves: a single text line, a stack of lines, a block, or a circle.
public enum ArenaSkeletonVariant: String, CaseIterable, Sendable {
    case text = "text"
    case line = "line"
    case block = "block"
    case circle = "circle"
}

/// Which way a column is ordered. Deliberately not ArenaDirection, which is a delta's arrow: up and down say which way a NUMBER moved, and ascending and descending say how a COLUMN is arranged. One set of names for both would read as the same idea in the two places it is not.
public enum ArenaSortDirection: String, CaseIterable, Sendable {
    case asc = "asc"
    case desc = "desc"
}

/// Colour for an indeterminate wait. 'accent' on a page surface, 'on-accent' inside a filled button. There is deliberately no success/warning/danger: a wait has no state to report, and a spinner tinted --danger would read as a failure that has not happened.
public enum ArenaSpinnerTone: String, CaseIterable, Sendable {
    case accent = "accent"
    case gold = "gold"
    case neutral = "neutral"
    case onAccent = "on-accent"
}

/// How a metric moved. Preformatted: ArenaStatCard never formats. The pill's colour says whether the change was GOOD, not which way it points, which is why direction and tone are separate fields.
public struct ArenaStatDelta: Sendable {
    /// Preformatted, e.g. "+12%" or "-340ms".
    public let value: String
    /// Which way the number moved. Draws the arrow: nothing else.
    public let direction: ArenaDirection
    /// Whether that movement is GOOD. Defaults to neutral: an unlabelled delta claims nothing.
    public let tone: ArenaDeltaTone?

    public init(
        value: String,
        direction: ArenaDirection,
        tone: ArenaDeltaTone? = nil
    ) {
        self.value = value
        self.direction = direction
        self.tone = tone
    }
}

/// The switch's overall size, from a dense sm to a prominent 2xl.
public enum ArenaSwitchSize: String, CaseIterable, Sendable {
    case sm = "sm"
    case md = "md"
    case lg = "lg"
    case xl = "xl"
    case size2xl = "2xl"
}

/// How an ArenaTable column's cells render in card mode: `row` is a label/value pair, `block` is a full-width strip with no label whose contents sit at the end of it, which is the shape an actions cell wants. A long value takes `row` or a cell of its own: set to `block` it draws with the whole gap on its leading side. Checked against every enum already declared here; nothing carries this pair. ArenaSkeletonVariant is the only other declaration containing the value `block`, and it names a shape of placeholder rather than a layout.
public enum ArenaTableCellLayout: String, CaseIterable, Sendable {
    case row = "row"
    case block = "block"
}

/// One column's configuration. A column says how its cells are headed and set, never what markup goes in them -- the consumer writes an ArenaTableCell per cell.
public struct ArenaTableColumn: Sendable {
    /// The column's label, drawn in the header row.
    public let header: String
    /// How this column's cells align.
    public let align: ArenaCellAlign?
    /// A fixed width for the column. Omit to let the table distribute.
    public let width: String?
    /// Draw this column's cells in the mono face, figure-aligned, and in the gold ink -- for identifiers and figures. The ink is the half that does not travel outside a table: gold reads as an identifier, so a sale total in gold inside a card says the wrong thing. Each layer offers the face and the digit alignment on their own, for a figure the consumer draws elsewhere, and its usage document says how.
    public let mono: Bool?
    /// Whether this column's header is an activation target. A declared boolean rather than "is sortChange bound?", because Arena never derives what it draws from what a consumer listens for, the same reason ArenaTableRow.interactive is one. It costs no tab stop: the header row is already row 0 of the grid's roving cursor, so a sortable header is activated with Enter or Space on the cell the user is already on. Without ArenaTable.sort no header is a target however many columns declare it, because a control that draws a direction it does not know is worse than no control.
    public let sortable: Bool?
    /// How this column renders in card mode: a label/value pair, or a full-width strip with no label whose contents sit at its end, which suits an actions cell rather than a long value.
    public let mobileLayout: ArenaTableCellLayout?

    public init(
        header: String,
        align: ArenaCellAlign? = nil,
        width: String? = nil,
        mono: Bool? = nil,
        sortable: Bool? = nil,
        mobileLayout: ArenaTableCellLayout? = nil
    ) {
        self.header = header
        self.align = align
        self.width = width
        self.mono = mono
        self.sortable = sortable
        self.mobileLayout = mobileLayout
    }
}

/// Which page of a longer list is on screen. Present, ArenaTable draws its own ArenaPagination below the grid and names it from `label`. ArenaTable does not slice: it does not hold the rows, so the consumer passes the page they already sliced and ArenaTable draws the control over it.
public struct ArenaTablePage: Sendable {
    /// The current page, 1-based, the same counting ArenaPagination uses.
    public let index: Double
    /// How many rows a full page holds. ArenaTable needs it to say how many pages there are, not to cut anything.
    public let size: Double
    /// How many rows there are across every page. Required because the projected children are one page and the count of pages cannot be derived from them; it is also what lets ArenaTable notice that the current page has gone PAST THE END and ask for page 1. That is the only reset ArenaTable performs, and it is the narrower half of the one a consumer writes: filtering ten pages down to five while the reader sits on the third leaves the page in range, so ArenaTable says nothing and the reader is on page three of results they did not ask for. Resetting on every change of total would be wrong, since removing one row from page three of ten must move nobody, and a count alone does not distinguish the two cases. Whether a change of CRITERION returns the reader to the first page is the consumer's question, because the consumer is the one holding the criterion.
    public let total: Double

    public init(
        index: Double,
        size: Double,
        total: Double
    ) {
        self.index = index
        self.size = size
        self.total = total
    }
}

/// Whether ArenaTable draws the pager it knows about. It is an enum rather than a boolean on the ArenaTableSortControl precedent, which this member is the second reading of: how a control is REACHED is a decision with room to grow, and the two members answer the same question about the two things a table's own chrome can hold.
public enum ArenaTablePageControl: String, CaseIterable, Sendable {
    case auto = "auto"
    case none = "none"
}

/// Where the projected rows sit inside a longer list. A reader is told the size of the whole collection and the position of each row within it whenever the rows on screen are only part of it, and a render that projects part of a list is that condition, so this is what those two announcements carry. Bound, it answers them whatever the consumer slices by. Absent with `page` bound, they are derived from the page, because a page IS a slice and stating it twice is how the two disagree. Absent with `page` absent, the projected rows are the whole list and neither is announced, which is the same answer the pattern gives for a grid holding every row it has.
public struct ArenaTableSlice: Sendable {
    /// How many rows the whole list holds, counting the ones nobody projected and not the header row, which ArenaTable adds itself because the announced count includes it. `-1` is the answer for a list whose length is not known yet, and it reaches the announcement unchanged: a feed that loads as it scrolls says -1 rather than a number it would have to invent and correct.
    public let total: Double
    /// How many rows of the whole list come before the first row projected here, counting from 0, so a window at the top of the list passes 0. The announced position is 1-based and the header row takes 1, so ArenaTable does that arithmetic rather than the consumer: an offset that already counted from 1 is counted twice, and the reader is told a position one row past where they are.
    public let offset: Double

    public init(
        total: Double,
        offset: Double
    ) {
        self.total = total
        self.offset = offset
    }
}

/// Which column the rows are ordered by, and which way. Controlled: ArenaTable draws the affordance and announces the order, and the consumer does the ordering, because ArenaTable does not hold the rows and pretending otherwise would be the error. Absent, no header is a sort target however many columns declare `sortable`.
public struct ArenaTableSort: Sendable {
    /// Which column, as its index in `columns`. An index rather than a key, because an ArenaTable's cells are already positional -- the nth ArenaTableCell takes the nth column -- so a key would be a second identity for a thing that already has one, and a required one on every column that a caller would have to invent.
    public let column: Double
    /// Which way that column is ordered.
    public let direction: ArenaSortDirection

    public init(
        column: Double,
        direction: ArenaSortDirection
    ) {
        self.column = column
        self.direction = direction
    }
}

/// How the sort affordance is reached in card mode, where there is no header row to activate. Above --bp-md the header row IS the control and this decides nothing.
public enum ArenaTableSortControl: String, CaseIterable, Sendable {
    case auto = "auto"
    case none = "none"
}

/// The tag's emphasis colour, per the ArenaBadge/ArenaTag tone taxonomy.
public enum ArenaTagTone: String, CaseIterable, Sendable {
    case neutral = "neutral"
    case primary = "primary"
    case success = "success"
    case warning = "warning"
    case danger = "danger"
}

/// Which corner the stack of notices is pinned to, block edge first. Checked against every enum already declared here before it was added; nothing carries this set. ArenaMenuAlign is the near miss and is a different question: it names which edge of a trigger a panel lines up with, on one axis, where this names a corner of the viewport and needs both. The inline half is `start`/`end` rather than left/right so a right-to-left reading flips it with the document.
public enum ArenaToastPlacement: String, CaseIterable, Sendable {
    case topStart = "top-start"
    case topEnd = "top-end"
    case bottomStart = "bottom-start"
    case bottomEnd = "bottom-end"
}

/// The side bar's colour. Narrower than ArenaTone: a toast reports an outcome, and there is no informational outcome a toast should interrupt for.
public enum ArenaToastTone: String, CaseIterable, Sendable {
    case neutral = "neutral"
    case success = "success"
    case danger = "danger"
    case gold = "gold"
}

/// What state a value IS in right now, as against how it moved. ArenaBadge's vocabulary, so one set of tone names covers the system rather than a second set that is nearly the same.
public enum ArenaTone: String, CaseIterable, Sendable {
    case neutral = "neutral"
    case accent = "accent"
    case gold = "gold"
    case success = "success"
    case warning = "warning"
    case danger = "danger"
    case info = "info"
}

/// When ArenaInput runs `validate`: on blur, or on every change.
public enum ArenaValidateOn: String, CaseIterable, Sendable {
    case blur = "blur"
    case change = "change"
}
