// GENERATED by bun run generate:tokens from the contract version repo.config.json pins.
// Edit the contract and raise the pin; an edit here survives until the next emit and then goes.
// Every doc comment below is that token's own $description, and check:doc-comments fails one that is not.

import Foundation
import SwiftUI

public struct ArenaDensityScale: Sendable {
    /// control height (buttons, inputs, switches row)
    public let ctlH: CGFloat
    public let ctlHLg: CGFloat
    public let ctlHSm: CGFloat
    /// glyph-tight line height: the control reset. Unlike every other dz member this is unitless, so it carries its own $type override: a line height is a number, not a dimension, the same distinction that puts lh in typography.json to begin with. Used wherever a box must be exactly its glyph (an icon inside a button, a standalone icon, an icon-only close/remove control), so the line box never throws the surrounding control out of alignment.
    public let lh: Double
    /// row horizontal padding
    public let rowPx: CGFloat
    /// table/list row vertical padding
    public let rowPy: CGFloat
    /// gap between stacked items
    public let stack: CGFloat
    /// control text: buttons, inputs, selects, menu items, table cells
    public let text: CGFloat
    /// column headers, row micro-labels, and a chart's axis ticks. It is also where step-label is born, so the whole label register sits here until a style plugin moves it
    public let text2xs: CGFloat
    /// the largest control text: a data readout inside a chart, where the number is the content rather than a label
    public let textLg: CGFloat
    /// secondary control text: tag chips, pagination, secondary buttons
    public let textMd: CGFloat
    /// secondary control text: hints, validation errors, badges, legends
    public let textSm: CGFloat
    /// micro control text: field labels, shortcuts, eyebrow labels, and the category and point labels of a chart, which are chrome under a plot rather than prose
    public let textXs: CGFloat

    public init(
        ctlH: CGFloat,
        ctlHLg: CGFloat,
        ctlHSm: CGFloat,
        lh: Double,
        rowPx: CGFloat,
        rowPy: CGFloat,
        stack: CGFloat,
        text: CGFloat,
        text2xs: CGFloat,
        textLg: CGFloat,
        textMd: CGFloat,
        textSm: CGFloat,
        textXs: CGFloat
    ) {
        self.ctlH = ctlH
        self.ctlHLg = ctlHLg
        self.ctlHSm = ctlHSm
        self.lh = lh
        self.rowPx = rowPx
        self.rowPy = rowPy
        self.stack = stack
        self.text = text
        self.text2xs = text2xs
        self.textLg = textLg
        self.textMd = textMd
        self.textSm = textSm
        self.textXs = textXs
    }
}

extension ArenaDensityScale {
    public static let base = ArenaDensityScale(
        ctlH: 40,
        ctlHLg: 48,
        ctlHSm: 32,
        lh: 1,
        rowPx: 16,
        rowPy: 12,
        stack: 12,
        text: 14,
        text2xs: 10,
        textLg: 16,
        textMd: 13,
        textSm: 12,
        textXs: 11
    )

    public static let compact = ArenaDensityScale(
        ctlH: 32,
        ctlHLg: 40,
        ctlHSm: 26,
        lh: 1,
        rowPx: 12,
        rowPy: 7,
        stack: 8,
        text: 13,
        text2xs: 10,
        textLg: 16,
        textMd: 12,
        textSm: 11,
        textXs: 10
    )

    public static let comfortable = ArenaDensityScale(
        ctlH: 48,
        ctlHLg: 56,
        ctlHSm: 44,
        lh: 1,
        rowPx: 20,
        rowPy: 16,
        stack: 16,
        text: 14,
        text2xs: 10,
        textLg: 16,
        textMd: 13,
        textSm: 12,
        textXs: 11
    )
}
