// GENERATED by bun run generate:tokens from the contract version repo.config.json pins.
// Edit the contract and raise the pin; an edit here survives until the next emit and then goes.
// Every doc comment below is that token's own $description, and check:doc-comments fails one that is not.

import Foundation
import SwiftUI

public enum ArenaTokens {
    public static let avatarLg: CGFloat = 56
    public static let avatarMd: CGFloat = 40
    public static let avatarSm: CGFloat = 32
    /// Script-readable, and so are its three siblings, for one reason: an <img>
    /// reserves its box before the stylesheet arrives through the width and height
    /// attributes, which take a bare integer and cannot take a custom property. So the
    /// number has to reach JavaScript or the avatar is the one image in the library
    /// whose space is not held. Reading it here rather than restating it in each layer
    /// is what keeps the reserved box and the drawn box the same number.
    public static let avatarXs: CGFloat = 24
    public static let bpLg: CGFloat = 1024
    public static let bpMd: CGFloat = 768
    public static let bpSm: CGFloat = 480
    /// Borders
    public static let bw: CGFloat = 1
    public static let bwStrong: CGFloat = 2
    /// The shortest chip that can carry its kebab below its title rather than
    /// beside it. Measured: 4px of padding, a 15px title line, the 32px kebab and 4px
    /// of padding again is 55px, rounded up to the 4px scale. Below it the two would
    /// overlap, so the chip keeps reserving a lateral band instead. Script-readable
    /// because it is compared against a projected pixel height.
    public static let calendarActionsBelowMinH: CGFloat = 56
    /// The width of the hour-label gutter down the left of the grid.
    /// Script-readable because the width term of arenaShowsTime() subtracts it from the
    /// measured container to get the grid's width, and no CSS expression hands a
    /// number to JS. It was calc(var(--sp-1) * 14) rendered inline: the same value in
    /// two idioms with nothing holding them in step. One token now, read both ways.
    public static let calendarGutterW: CGFloat = 56
    /// The pixel height of one hour. Script-readable because
    /// y = ((min - startMin) / 60) * hour-h is arithmetic, and no CSS expression
    /// computes a position from a minute-of-day. An orphan before this: --sp-10 is 40
    /// and --sp-12 is 48, so nothing in the spacing scale was 44.
    public static let calendarHourH: CGFloat = 44
    /// The shortest chip that still draws its time label. Below it there is no
    /// room for a second line. Script-readable because it is compared against a
    /// projected pixel height; it was a bare 32 in the render body, invisible to
    /// check:dimensions, which reads governed CSS properties and never a comparison.
    public static let calendarTimeMinH: CGFloat = 32
    /// The narrowest column share a chip may occupy and still draw its time
    /// label. Measured: the label is 78.02px at --dz-text-2xs, and a chip's content box
    /// is its share less 18px -- 4px of gutter to its neighbour, 12px of its own
    /// padding, 2px of its left border -- so 96.02px, rounded up to the 4px scale. The
    /// threshold is on the share rather than on the chip so that ArenaCalendar never has to
    /// know ArenaCalendarEvent's padding.
    public static let calendarTimeMinW: CGFloat = 100
    /// Surface between bars. Equals --bw-strong, coincidentally.
    public static let chartBarGap: CGFloat = 2
    /// A bar's data end. Deliberately NOT --r-sm (6px): naming the value Arena
    /// already renders is free, snapping to the radius scale is a visible 2px design
    /// change and must be taken as one.
    public static let chartBarRadius: CGFloat = 4
    /// A bubble at the largest value it carries. The pair is a RADIUS range and the
    /// mapping between them is by area, not by radius: doubling a radius quadruples the blot, and a
    /// reader compares the blot, so a linear radius exaggerates the large value by a factor of four.
    /// Sixteen is what fits the size key beside the series names without either crowding the other,
    /// and it is a chosen dimension rather than a consequence, unlike the pads.
    public static let chartBubbleRMax: CGFloat = 16
    /// A bubble at the smallest value it carries. Equals point-r, deliberately: a bubble
    /// chart with one size in it is a scatter, and it should draw like one rather than jumping to
    /// some other mark size the moment a third column appears.
    public static let chartBubbleRMin: CGFloat = 4
    /// Plot height before padding.
    public static let chartHeight: CGFloat = 280
    /// Between an axis label and the plot it labels: a y-axis tick label ends this far
    /// left of pad-left, and an x-axis category label sits this far above the bottom
    /// edge. It is a spacing decision, so it is a token by the same criterion the pads
    /// are.
    public static let chartLabelGap: CGFloat = 8
    /// Between the doughnut plot and its legend.
    public static let chartLegendGap: CGFloat = 16
    /// Doughnut legend, widest.
    public static let chartLegendMax: CGFloat = 180
    /// Doughnut legend, narrowest.
    public static let chartLegendMin: CGFloat = 120
    /// The row of series keys a cartesian chart draws below its plot, height including
    /// the separation from the plot. A CONSEQUENCE of the type scale rather than a chosen
    /// dimension, the way pad-bottom is: one line at --dz-text-sm stands 18px at the root line
    /// height, the swatch beside it is smaller and rides inside that line, and one step of the base
    /// grid separates the row from the plot. If the type scale moves, revisit it; it will not fail
    /// loudly.
    /// It comes OUT of the plot rather than being added to the chart's box, so --chart-height stays
    /// the height of the whole component whether a legend is drawn or not. That is the same trade
    /// the doughnut already makes on the other axis, where the legend column takes its width from
    /// the ring rather than from the caller.
    public static let chartLegendStrip: CGFloat = 26
    /// Holds the category labels. This is a CONSEQUENCE of the type scale, not a
    /// chosen dimension: it is enough room for a label at --dz-text-xs, which is the step a
    /// category label takes because a name under a plot is chrome and not prose. If the type
    /// scale moves, revisit it; it will not fail loudly.
    /// The labels stay on this edge whatever the data does, so a bar growing down from a
    /// zero line above the floor runs toward them. That is deliberate: a reader looks for
    /// category labels along the bottom, and moving them to follow the zero line would put
    /// them somewhere different in every chart on a page. What it costs is a downward bar
    /// reaching its label at the extreme of the axis, which is the price of one place to
    /// look.
    public static let chartPadBottom: CGFloat = 28
    /// Holds the category names down the left edge of a horizontal bar chart, where
    /// pad-left holds value labels on a vertical one. A separate token rather than a wider
    /// pad-left, because the two hold different things and sizing every chart's value gutter for
    /// the longest category name anyone might write would waste 52px on every vertical chart in
    /// the library. A CONSEQUENCE of the type scale like pad-bottom, and a soft one: a name longer
    /// than it fits is truncated rather than overrunning the plot, so this is the width at which a
    /// reader stops needing the tooltip to read a label, not a limit on what may be passed.
    public static let chartPadCategory: CGFloat = 96
    /// Holds the value labels. A consequence of the type scale, like pad-bottom.
    public static let chartPadLeft: CGFloat = 44
    /// The plot's right padding, one step of the base grid.
    public static let chartPadRight: CGFloat = 8
    /// The plot's top padding, one step of the base grid.
    public static let chartPadTop: CGFloat = 8
    /// A line chart's point at rest.
    public static let chartPointR: CGFloat = 4
    /// A line chart's point under the pointer. The 1px delta IS the hover
    /// affordance: the pair only means anything together.
    public static let chartPointRHover: CGFloat = 5
    /// Breathing room between the doughnut's outer radius and its box, so a slice's
    /// stroke is not clipped. Not a multiplier deriving one dimension from another --
    /// those stay inline by the recorded criterion -- but a chosen gap, which is why
    /// this one is a token and the 0.62 inner-radius ratio beside it is not.
    public static let chartRingInset: CGFloat = 8
    /// Between two bars of the same category, when a chart draws more than one series.
    /// Distinct from bar-gap, which is between categories, and deliberately smaller than it:
    /// the wider gap is what tells a reader where one category ends, and if the two were equal
    /// a grouped chart would read as one long row of unrelated bars. Script-readable, because
    /// JS subtracts it from a sub-band width to produce an SVG x.
    public static let chartSeriesGap: CGFloat = 1
    /// The advance of one character of a tick label, which is what lets the axis measure
    /// its widest tick without a DOM to ask. A CONSEQUENCE of two decisions rather than a
    /// chosen dimension: a tick is written in the mono face, whose advance is 0.6em, at
    /// --dz-text-2xs, which is 10px in both densities. Measured in the browser at 6.0016px
    /// and rounded down to the whole pixel, because the gutter takes the ceiling of what it
    /// computes and a hundredth of a pixel per character is not room anybody can see. It
    /// holds only while the ticks stay monospaced: a proportional face makes a label's width
    /// its glyphs' business and no arithmetic can answer it.
    public static let chartTickChar: CGFloat = 6
    /// Between the mark under the pointer and the tooltip's near edge. Not script-readable:
    /// the chart interpolates the mark's own y into a calc() and CSS subtracts this from it, so
    /// the stylesheet is what consumes the token. It settles a disagreement rather than recording
    /// one: the bar chart offset its tooltip by --sp-2 and the line chart by 2.5 steps of --sp-1,
    /// which is 10px against 8px for the same affordance. Naming it moves the line chart's tooltip
    /// 2px, and that is a visible design change taken deliberately, the same way chart.bar-radius
    /// refuses to snap to --r-sm because doing so would be one.
    public static let chartTooltipOffset: CGFloat = 8
    /// Grace period after the pointer leaves. Short, and much shorter than open:
    /// it exists so travelling between a trigger and its own tooltip does not dismiss it,
    /// not to keep the tooltip around.
    public static let delayClose: TimeInterval = 0.12
    /// Rest time before a tooltip appears. Long enough that crossing a toolbar reveals nothing.
    public static let delayOpen: TimeInterval = 0.4
    /// A toast carrying a button. WCAG 2.2.1: it asks the reader to DECIDE, not
    /// only to read, and 4.2s is enough for the second task only if they were already
    /// looking. persist (README H1) still overrides both and stays mandatory in
    /// critical states.
    public static let dismissActionable: TimeInterval = 7
    /// A toast that only has to be read. This is the value the Delivery Console
    /// shipped hard-coded before it was a token.
    public static let dismissDefault: TimeInterval = 4.2
    public static let durFast: TimeInterval = 0.12
    public static let durMid: TimeInterval = 0.22
    public static let durSlow: TimeInterval = 0.42
    /// the "rotor" flourish
    public static let easeEmphatic: ArenaEasing = ArenaEasing(x1: 0.2, y1: 0.9, x2: 0.1, y2: 1)
    public static let easeInOut: ArenaEasing = ArenaEasing(x1: 0.4, y1: 0, x2: 0.2, y2: 1)
    public static let easeOut: ArenaEasing = ArenaEasing(x1: 0.2, y1: 0.7, x2: 0.3, y2: 1)
    public static let focusOffset: CGFloat = 2
    public static let focusWidth: CGFloat = 2
    /// legible body copy
    public static let fontBody: String = "Familjen Grotesk"
    /// impact: headlines, wordmark
    public static let fontDisplay: String = "Archivo"
    /// data, technical labels
    public static let fontMono: String = "Spline Sans Mono"
    /// large display heading
    public static let fsDisplay: CGFloat = 64
    public static let fsH1: CGFloat = 44
    public static let fsH2: CGFloat = 32
    public static let fsH3: CGFloat = 24
    public static let fsH4: CGFloat = 19
    /// extrapolated step between display (64) and mega (150) that keeps the scale's accelerating ratio coherent through its top; added with no consumer today by design: do not delete as dead API
    public static let fsHero: CGFloat = 96
    public static let fsLg: CGFloat = 17
    /// body copy
    public static let fsMd: CGFloat = 15
    /// largest display step: the brand manual's .big-glyph specimen
    public static let fsMega: CGFloat = 150
    public static let fsSm: CGFloat = 13
    /// mono labels / captions
    public static let fsXs: CGFloat = 11
    public static let fwBlack: Font.Weight = .black
    public static let fwBold: Font.Weight = .bold
    public static let fwExtrabold: Font.Weight = .heavy
    public static let fwMedium: Font.Weight = .medium
    public static let fwRegular: Font.Weight = .regular
    public static let fwSemibold: Font.Weight = .semibold
    public static let iconLg: CGFloat = 18
    public static let iconMd: CGFloat = 16
    public static let iconSm: CGFloat = 14
    /// Illustration-scale icon (ArenaEmptyState, ArenaErrorState): a distinct role from the 14/16/18 inline-control cluster.
    public static let iconXl: CGFloat = 34
    /// The height of a fixed bottom navigation bar, the row of destinations a
    /// phone shell puts at the foot of the screen. It is read from outside the bar as often
    /// as inside it: the page reserves it as bottom padding so the last row is not covered,
    /// and a stack of toasts sits above it rather than under it, so a bar whose height only
    /// the bar knows is a number retyped in three files. The safe-area inset is NOT included:
    /// add the bottom safe area to it, which ArenaSafeArea.bottom composes, since a value that
    /// already carried the inset could not be used as a plain height. Nothing computes a
    /// position from it, and a value bound at import time could not re-densify.
    public static let layoutBar: CGFloat = 64
    /// The width of the console shell's navigation column.
    public static let layoutSidebar: CGFloat = 232
    public static let lhBody: Double = 1.6
    /// Reading leading for a style plugin that carries its hierarchy in type rather than in boxes.
    /// One step above body, which is where a page of prose stops being a panel of copy.
    public static let lhLoose: Double = 1.8
    /// What every element inherits until something declares otherwise. It is not a role like the three below, which a component picks on purpose; it is the floor, and it exists because a floor that each platform gets from somewhere else is a floor the two do not share. Tailwind's preflight sets exactly this number, so the Angular layer already had it and React, which loads no preflight, inherited the browser's `normal` instead: the same text stood about 7% shorter there, across 94 slots in 32 components, and nothing said so. Arena declares it now, in contracts/design/reset.css, so both layers inherit one value. The number matches what was already shipping rather than being chosen afresh.
    public static let lhRoot: Double = 1.5
    public static let lhSnug: Double = 1.15
    public static let lhTight: Double = 0.98
    /// How many page numbers flank the current one before the list elides. The
    /// window's total width is a CONSEQUENCE and is derived at the point of use, never
    /// authored: first + last + (2 * siblings + 1) + two ellipses.
    public static let limitPaginationSiblings: Double = 1
    /// the manual's Primary · horizontal
    public static let logoMarkLg: CGFloat = 54
    /// a signed-out panel's lock-up
    public static let logoMarkMd: CGFloat = 40
    /// beside a product name in an application frame
    public static let logoMarkSm: CGFloat = 30
    /// the hero case: the lock-up is the only thing on the screen
    public static let logoMarkXl: CGFloat = 124
    /// the wordmark beside mark-lg, in the manual's Primary · horizontal
    public static let logoTextLg: CGFloat = 34
    /// the wordmark beside mark-md, in a signed-out panel
    public static let logoTextMd: CGFloat = 24
    /// the wordmark beside mark-sm: the smallest that still reads as a name rather than a label
    public static let logoTextSm: CGFloat = 17
    /// the wordmark beside mark-xl, at hero size
    public static let logoTextXl: CGFloat = 78
    /// Rotor: slow enough to read as presence rather than progress
    public static let loopBrand: TimeInterval = 8
    /// Rotor's reduced step: the brand mark is three times slower again, because it is decoration that happens to also mean 'alive'
    public static let loopBrandReduced: TimeInterval = 24
    /// What a working loop slows to when the reader has asked for less movement. Motion that reports work slows rather than stopping: a frozen spinner reads as a hung process, which is what ArenaMotion.working composes this step for.
    public static let loopReduced: TimeInterval = 2.4
    /// ArenaSkeleton
    public static let loopShimmer: TimeInterval = 1.4
    /// ArenaSpinner, and ArenaButton's loading ring
    public static let loopSpin: TimeInterval = 0.7
    /// ArenaProgressBar's indeterminate sweep
    public static let loopSweep: TimeInterval = 1.15
    /// badge and pill text
    public static let lsBadge: CGFloat = 0.1
    /// column header / micro-label
    public static let lsColumnHeader: CGFloat = 0.12
    /// form field label
    public static let lsFieldLabel: CGFloat = 0.14
    /// mono uppercase labels: section eyebrows
    public static let lsLabel: CGFloat = 0.22
    /// mono navigation: breadcrumbs, bulk-action counts
    public static let lsMonoNav: CGFloat = 0.04
    public static let lsNormal: CGFloat = 0
    /// display: tight headings
    public static let lsTight: CGFloat = -0.02
    /// uppercase status text: alerts, toasts, calendar hour labels
    public static let lsUppercaseStatus: CGFloat = 0.06
    /// eyebrows
    public static let lsWide: CGFloat = 0.34
    /// How much room the popover keeps below its anchor before it stops following it
    /// down the viewport. Script-readable for the same reason width is: it is compared
    /// against window.innerHeight in JS. It sat inline in both layers as a bare 220
    /// beside a bare 900, and only one of the two is a design value -- 900 is an
    /// SSR fallback for a viewport height nobody chose.
    public static let onboardingHeightReserve: CGFloat = 220
    /// The popover's width. Script-readable because Math.min/Math.max compare it
    /// against window.innerWidth. This ALSO replaces the calc(var(--sp-1) * 80) the
    /// component rendered: the value existed twice in two idioms, held in step by a
    /// comment. One token now, read both ways.
    public static let onboardingWidth: CGFloat = 320
    /// splash tile: distinct from xl's app icon tile
    public static let r2xl: CGFloat = 34
    /// cards, panels
    public static let rLg: CGFloat = 14
    /// nested cards, menus
    public static let rMd: CGFloat = 10
    public static let rPill: CGFloat = 999
    /// buttons, inputs, chips
    public static let rSm: CGFloat = 6
    /// app icon tile
    public static let rXl: CGFloat = 22
    public static let rXs: CGFloat = 4
    /// Between two peer components: a card and the next card, a chart and the table under it. Both sides are separate things standing on the same footing.
    public static let rhythmComponent: CGFloat = 16
    /// Inside one group of related things: a label and its field, a card's own stacked children, a row of chips. Both sides read as one unit.
    public static let rhythmGroup: CGFloat = 12
    /// Between two sections of a page. The two sides answer different questions, and this gap is what says so.
    public static let rhythmSection: CGFloat = 24
    /// Overlay scrim: backdrop for anything that covers the app (ArenaDialog,
    /// ConfirmDialog, ArenaCommandPalette, ArenaOnboarding). The blur is what separates a
    /// modal from a coachmark: ArenaDialog/ArenaConfirmDialog/ArenaCommandPalette pair the scrim
    /// with --scrim-blur, ArenaOnboarding uses the scrim alone, because a tour that
    /// blurs the product it is touring defeats itself.
    public static let scrim: Color = Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 0.6)
    public static let scrimBlur: CGFloat = 6
    public static let shadow1: ArenaShadow = ArenaShadow(offsetX: 0, offsetY: 2, blur: 6, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.5))
    public static let shadow2: ArenaShadow = ArenaShadow(offsetX: 0, offsetY: 12, blur: 28, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.6))
    public static let shadow3: ArenaShadow = ArenaShadow(offsetX: 0, offsetY: 30, blur: 60, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.7))
    public static let sp0: CGFloat = 0
    /// Script-readable: ArenaMenu's gap from its trigger is one and a half of this, and that gap is the offset a CDK overlay position strategy computes in JS, so no stylesheet can hold it.
    public static let sp1: CGFloat = 4
    public static let sp10: CGFloat = 40
    public static let sp12: CGFloat = 48
    public static let sp16: CGFloat = 64
    /// Script-readable: ArenaTooltip's gap from its trigger is the offset a CDK overlay position strategy computes in JS, so no stylesheet can hold it.
    public static let sp2: CGFloat = 8
    public static let sp20: CGFloat = 80
    public static let sp24: CGFloat = 96
    /// Script-readable: ArenaOnboarding's gap below its anchor is arithmetic on a DOMRect.
    public static let sp3: CGFloat = 12
    /// Script-readable: ArenaOnboarding's minimum gutter from either viewport edge, compared against window.innerWidth.
    public static let sp4: CGFloat = 16
    public static let sp5: CGFloat = 20
    public static let sp6: CGFloat = 24
    public static let sp8: CGFloat = 32
    /// Fill under a line chart's series. A tint, never a gradient.
    public static let tintArea: CGFloat = 0.18
    /// The hairline around that surface. It reads as the same colour only because
    /// it is roughly twice soft: a border at the surface's own ratio disappears.
    public static let tintEdge: CGFloat = 0.26
    /// The surface an identity colour stands on: light enough that text at the
    /// body contrast keeps its ratio over it, which is why it is well under area.
    public static let tintSoft: CGFloat = 0.12
    /// ArenaMenu's panel: a dropdown anchored to its trigger
    public static let zDropdown: Double = 900
    /// ArenaDialog
    public static let zModal: Double = 1000
    /// ArenaConfirmDialog, which opens from an ArenaDialog
    public static let zModalNested: Double = 1050
    /// Fixed page navigation: a bottom bar, a sticky top bar. Arena draws one of these, ArenaBottomNav, and the slot is not there for it: it is there because the invariant is system-wide and a consumer's own shell is part of the system, so a host's sticky header and Arena's bar interleave with Arena's overlays by design rather than by stacking order. That was the reason before any component carried it and it is the reason still; what changed is only that the set of things standing on this step is no longer empty. Below dropdown, so an ArenaMenu opened from the bar covers it rather than resolving by the order it was drawn in, which is the failure this family was created to end. Anything drawn against this slot also reads the bottom safe area, which ArenaSafeArea.bottom composes, and layoutBar for its own height
    public static let zNav: Double = 800
    /// the coachmark and the scrim beneath it: one slot, two uses. The scrim takes the slot and the coachmark is drawn inside it, so the two are separated by containment rather than by a second number; nothing else on the page may sit between them, which is what a single slot means here
    public static let zOnboarding: Double = 1200
    /// ArenaCommandPalette
    public static let zPalette: Double = 1100
    /// A non-modal panel anchored to an edge: a cart, a filter drawer, a detail pane that leaves the page usable behind it. Arena draws one of these, ArenaSheet, and the slot exists for the same reason nav does: a host's own edge panel stands beside it on the same step. Above nav, because a sheet that slides over a fixed bar and lands under it is the failure; below dropdown, because an ArenaMenu opened from inside the sheet belongs over it. It is NOT modal: a panel that takes the whole interaction is an ArenaDialog, which is two slots higher and has a scrim to say so
    public static let zSheet: Double = 850
    /// The skip link, while it holds focus. It is the one thing on the page that must cover the furniture it exists to bypass: a link that lands under a sticky header is a link nobody can read, and equal numbers resolve by DOM order, which puts the header on top because the skip link is deliberately first in the document. So it is above nav and no higher: everything from sheet upward is a surface that has taken the interaction, and a skip link floating over a modal is a route out of a trap that is meant to hold
    public static let zSkip: Double = 820
    /// floats above everything, including onboarding: a transient notice raised by an action taken inside a dialog must stay visible
    public static let zToast: Double = 1300
    /// above dropdown, so a tooltip on a menu item wins
    public static let zTooltip: Double = 950
}
