// GENERATED by bun run generate:tokens from the contract version repo.config.json pins.
// Edit the contract and raise the pin; an edit here survives until the next emit and then goes.
// Every doc comment below is that token's own $description, and check:doc-comments fails one that is not.

import Foundation
import SwiftUI

public struct ArenaColorScheme: Sendable {
    /// main background
    public let base100: Color
    /// elevated surface / card
    public let base200: Color
    /// panel / border
    public let base300: Color
    /// text on base
    public let baseContent: Color
    /// Categorical chart ramp: identity only, never meaning (see README → Theming).
    /// Fixed order: slot N is always slot N. A 9th series folds to "Other", small
    /// multiples, or direct labels; it is NEVER a generated hue.
    /// Chroma is capped at OKLCH C <= 0.15 so the ramp sits in Arena's register
    /// (crimson .177, gold .100) instead of reading as neon.
    /// forest  136°
    public let cat1: Color
    /// indigo  264°
    public let cat2: Color
    /// green   152°
    public let cat3: Color
    /// violet  288°
    public let cat4: Color
    /// cyan    216°
    public let cat5: Color
    /// purple  312°
    public let cat6: Color
    /// teal    184°
    public let cat7: Color
    /// orchid  328°
    public let cat8: Color
    /// Outline danger: this red IS the text and the border, so it is tuned against
    /// the base surfaces, lighter than the shared #e53e3e it replaced (4.29:1 on
    /// base-200: under AA).
    public let error: Color
    public let errorContent: Color
    /// Filled danger. --color-error is tuned to be read AS TEXT on the base
    /// surfaces, which makes it far too light to carry white text itself. The one
    /// filled danger surface (ArenaConfirmDialog's final confirmation) therefore takes
    /// its own fill, dark enough for --color-error-content. The two cannot be one
    /// token: the outline needs a lighter red and the fill a darker one, in
    /// opposite directions. This pin is OPTIONAL: omit it and colors.css derives
    /// the fill from --color-error by darkening in oklab; the Dravensoft skin pins
    /// it for an exact tone. Both gates are machine-checked: check-text-contrast.ts.
    public let errorFill: Color
    public let info: Color
    public let infoContent: Color
    /// neutral surface
    public let neutral: Color
    public let neutralContent: Color
    /// crimson
    public let primary: Color
    public let primaryContent: Color
    /// gold
    public let secondary: Color
    public let secondaryContent: Color
    public let success: Color
    public let successContent: Color
    public let warning: Color
    public let warningContent: Color

    public init(
        base100: Color,
        base200: Color,
        base300: Color,
        baseContent: Color,
        cat1: Color,
        cat2: Color,
        cat3: Color,
        cat4: Color,
        cat5: Color,
        cat6: Color,
        cat7: Color,
        cat8: Color,
        error: Color,
        errorContent: Color,
        errorFill: Color,
        info: Color,
        infoContent: Color,
        neutral: Color,
        neutralContent: Color,
        primary: Color,
        primaryContent: Color,
        secondary: Color,
        secondaryContent: Color,
        success: Color,
        successContent: Color,
        warning: Color,
        warningContent: Color
    ) {
        self.base100 = base100
        self.base200 = base200
        self.base300 = base300
        self.baseContent = baseContent
        self.cat1 = cat1
        self.cat2 = cat2
        self.cat3 = cat3
        self.cat4 = cat4
        self.cat5 = cat5
        self.cat6 = cat6
        self.cat7 = cat7
        self.cat8 = cat8
        self.error = error
        self.errorContent = errorContent
        self.errorFill = errorFill
        self.info = info
        self.infoContent = infoContent
        self.neutral = neutral
        self.neutralContent = neutralContent
        self.primary = primary
        self.primaryContent = primaryContent
        self.secondary = secondary
        self.secondaryContent = secondaryContent
        self.success = success
        self.successContent = successContent
        self.warning = warning
        self.warningContent = warningContent
    }
}

extension ArenaColorScheme {
    public static let dark = ArenaColorScheme(
        base100: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1),
        base200: Color(.sRGB, red: 0.1137, green: 0.0902, blue: 0.0824, opacity: 1),
        base300: Color(.sRGB, red: 0.1412, green: 0.1098, blue: 0.098, opacity: 1),
        baseContent: Color(.sRGB, red: 0.9529, green: 0.9294, blue: 0.898, opacity: 1),
        cat1: Color(.sRGB, red: 0.2353, green: 0.4824, blue: 0.0392, opacity: 1),
        cat2: Color(.sRGB, red: 0.2314, green: 0.3882, blue: 0.7451, opacity: 1),
        cat3: Color(.sRGB, red: 0.0392, green: 0.5725, blue: 0.2941, opacity: 1),
        cat4: Color(.sRGB, red: 0.4157, green: 0.349, blue: 0.7373, opacity: 1),
        cat5: Color(.sRGB, red: 0, green: 0.6392, blue: 0.7529, opacity: 1),
        cat6: Color(.sRGB, red: 0.5333, green: 0.302, blue: 0.6627, opacity: 1),
        cat7: Color(.sRGB, red: 0, green: 0.6627, blue: 0.6039, opacity: 1),
        cat8: Color(.sRGB, red: 0.5961, green: 0.2745, blue: 0.5922, opacity: 1),
        error: Color(.sRGB, red: 0.9098, green: 0.3176, blue: 0.3176, opacity: 1),
        errorContent: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
        errorFill: Color(.sRGB, red: 0.8078, green: 0.2196, blue: 0.2196, opacity: 1),
        info: Color(.sRGB, red: 0.1922, green: 0.5098, blue: 0.8078, opacity: 1),
        infoContent: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1),
        neutral: Color(.sRGB, red: 0.1725, green: 0.1333, blue: 0.1176, opacity: 1),
        neutralContent: Color(.sRGB, red: 0.8471, green: 0.8118, blue: 0.7686, opacity: 1),
        primary: Color(.sRGB, red: 0.7098, green: 0.1647, blue: 0.1255, opacity: 1),
        primaryContent: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
        secondary: Color(.sRGB, red: 0.7725, green: 0.6275, blue: 0.349, opacity: 1),
        secondaryContent: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1),
        success: Color(.sRGB, red: 0.2196, green: 0.6314, blue: 0.4118, opacity: 1),
        successContent: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1),
        warning: Color(.sRGB, red: 0.9255, green: 0.7882, blue: 0.2941, opacity: 1),
        warningContent: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1)
    )

    public static let light = ArenaColorScheme(
        base100: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
        base200: Color(.sRGB, red: 0.9686, green: 0.9569, blue: 0.9373, opacity: 1),
        base300: Color(.sRGB, red: 0.9255, green: 0.902, blue: 0.8627, opacity: 1),
        baseContent: Color(.sRGB, red: 0.102, green: 0.102, blue: 0.102, opacity: 1),
        cat1: Color(.sRGB, red: 0.2235, green: 0.4706, blue: 0.0157, opacity: 1),
        cat2: Color(.sRGB, red: 0.149, green: 0.2941, blue: 0.6431, opacity: 1),
        cat3: Color(.sRGB, red: 0.0392, green: 0.5725, blue: 0.2941, opacity: 1),
        cat4: Color(.sRGB, red: 0.3216, green: 0.2431, blue: 0.6235, opacity: 1),
        cat5: Color(.sRGB, red: 0, green: 0.5608, blue: 0.6627, opacity: 1),
        cat6: Color(.sRGB, red: 0.4314, green: 0.1961, blue: 0.5529, opacity: 1),
        cat7: Color(.sRGB, red: 0, green: 0.5804, blue: 0.5294, opacity: 1),
        cat8: Color(.sRGB, red: 0.4863, green: 0.1686, blue: 0.4824, opacity: 1),
        error: Color(.sRGB, red: 0.7647, green: 0.2078, blue: 0.2078, opacity: 1),
        errorContent: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
        errorFill: Color(.sRGB, red: 0.8078, green: 0.2196, blue: 0.2196, opacity: 1),
        info: Color(.sRGB, red: 0.1922, green: 0.5098, blue: 0.8078, opacity: 1),
        infoContent: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1),
        neutral: Color(.sRGB, red: 0.7922, green: 0.7373, blue: 0.6784, opacity: 1),
        neutralContent: Color(.sRGB, red: 0.2275, green: 0.1804, blue: 0.1608, opacity: 1),
        primary: Color(.sRGB, red: 0.7098, green: 0.1647, blue: 0.1255, opacity: 1),
        primaryContent: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
        secondary: Color(.sRGB, red: 0.7725, green: 0.6275, blue: 0.349, opacity: 1),
        secondaryContent: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1),
        success: Color(.sRGB, red: 0.2196, green: 0.6314, blue: 0.4118, opacity: 1),
        successContent: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1),
        warning: Color(.sRGB, red: 0.9255, green: 0.7882, blue: 0.2941, opacity: 1),
        warningContent: Color(.sRGB, red: 0.0784, green: 0.0627, blue: 0.0627, opacity: 1)
    )
}
